# Generate RecheckBuiltins.codex -- the builtin NAME list, and nothing else.
#
# The rechecker needs to answer "does this identifier exist" when it walks a
# body looking for free variables. That is a fact about what the language
# provides, not a judgement about types, so taking the names is inside the
# independence rule in docs/Designs/Active/Tools/IndependentRechecker.md
# section 7 and taking bs-type would not be. A builtin's type at a call site
# comes off the wire, because what stage 1 checks is whether an application
# agrees with the types the IR itself asserts.
#
# Generated and checked in, with build.ps1 re-running this and failing on any
# difference. That is build/check-cdx-registry.ps1's pattern and it exists for
# the same reason: a table nothing reads drifts from the code it describes,
# and here the drift direction is dangerous -- a builtin missing from this list
# becomes a DISAGREE against a program that is fine.
#
#   pwsh codex/plugs/recheck/gen-builtins.ps1            # write the chapter
#   pwsh codex/plugs/recheck/gen-builtins.ps1 -Check     # exit 1 if it differs
[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Repo    = (Resolve-Path (Join-Path $PSScriptRoot '..' '..' '..')).Path
$Source  = Join-Path $Repo 'codex\compiler\Types\Builtins.codex'
$Target  = Join-Path $PSScriptRoot 'RecheckBuiltins.codex'

if (-not (Test-Path -PathType Leaf $Source)) {
    [Console]::Error.WriteLine("gen-builtins: missing $Source")
    exit 1
}

$names = [regex]::Matches((Get-Content -Raw $Source), 'bs-name\s*=\s*"([^"]+)"') |
         ForEach-Object { $_.Groups[1].Value } |
         Sort-Object -Unique

if ($names.Count -eq 0) {
    [Console]::Error.WriteLine("gen-builtins: extracted 0 names -- the row shape in Builtins.codex changed")
    exit 1
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('Chapter: RecheckBuiltins')
[void]$sb.AppendLine('')
[void]$sb.AppendLine(' GENERATED by codex/plugs/recheck/gen-builtins.ps1. Do not edit by hand.')
[void]$sb.AppendLine(' The names the compiler provides as builtins, so the well-formedness walk')
[void]$sb.AppendLine(' can tell an unbound identifier from one the language supplies. Names only:')
[void]$sb.AppendLine(' a builtin type is never read from here, it is read off the wire.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Section: The Names')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('  recheck-builtin-names : List Text')
[void]$sb.AppendLine('  recheck-builtin-names = [')
for ($i = 0; $i -lt $names.Count; $i++) {
    $comma = if ($i -lt $names.Count - 1) { ',' } else { ''
    }
    [void]$sb.AppendLine('   "' + $names[$i] + '"' + $comma)
}
[void]$sb.AppendLine('  ]')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Page 1')

$body = $sb.ToString() -replace "`r`n", "`n"

if ($Check) {
    if (-not (Test-Path -PathType Leaf $Target)) {
        [Console]::Error.WriteLine("gen-builtins -Check: $Target does not exist; run without -Check")
        exit 1
    }
    $have = (Get-Content -Raw $Target) -replace "`r`n", "`n"
    if ($have -ne $body) {
        [Console]::Error.WriteLine("gen-builtins -Check: RecheckBuiltins.codex is STALE against Builtins.codex.")
        [Console]::Error.WriteLine("  Regenerate: pwsh codex/plugs/recheck/gen-builtins.ps1")
        exit 1
    }
    Write-Host "gen-builtins: OK ($($names.Count) builtin names, in step with Builtins.codex)"
    exit 0
}

[System.IO.File]::WriteAllText($Target, $body, [System.Text.UTF8Encoding]::new($false))
Write-Host "gen-builtins: wrote $Target ($($names.Count) names)"
