import {readFileSync,mkdtempSync,createReadStream,writeFileSync} from 'node:fs';
import {join,resolve,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {spawn,execFileSync,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import http from 'node:http';

const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const [htmlPath,referencePath,outPath,evidencePath,widthArg='1024',heightArg='1024',sampler='Euler']=process.argv.slice(2);
if(!evidencePath)throw new Error('Usage: node apps/spark/studio-sdxl.mjs studio.html native.png saved.png reference-evidence.json [width height sampler]');
const samplerIds={'Euler':0,'DPM++ 2M':2,'DPM++ SDE':1,'DPM++ 2M SDE':3,'DPM++ 2M SDE Heun':4,'DPM++ 3M SDE':6};
if(!Object.hasOwn(samplerIds,sampler))throw Error('Choose a supported Studio SDXL sampler');
const samplerId=samplerIds[sampler];
const targetWidth=Number(widthArg),targetHeight=Number(heightArg),size=targetWidth+'x'+targetHeight;
if(!['1024x1024','1024x768','768x1024','1344x768','768x1344'].includes(size))throw Error('Choose a Studio SDXL preset');
const ckpt=join(repo,'build-output/diffusion-models/dreamshaperXL_lightningDPMSDE.safetensors');
const checkpointHash=createHash('sha256');for await(const bytes of createReadStream(ckpt))checkpointHash.update(bytes);
const checkpointSha256=checkpointHash.digest('hex');console.log('Checkpoint SHA256 '+checkpointSha256);
const prompt='painterly fantasy concept art, norse viking theme, warm firelight against cold blue night, cinematic lighting, rich detail, game key art, four iron-bound wooden chests around a carpenter workbench, joined by glowing golden rune threads, inside a torch-lit longhouse';
const negative='text, letters, words, watermark, signature, logo, ui, blurry, deformed, ugly, lowres, jpeg artifacts, photo, photograph, modern';
const promptFile=['PROMPT 01 '+String.fromCharCode(0x2014)+' "Storage"','',prompt,''].join(String.fromCharCode(10));
const expectedParameters=prompt+'\nNegative prompt: '+negative+'\nSteps: 6, Sampler: '+sampler+', Schedule type: Karras, CFG scale: 2, Seed: 7201, Size: '+size+', Model: dreamshaperXL_lightningDPMSDE';
const reference=readFileSync(referencePath);let parameters='',width=0,height=0;
if(reference.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw new Error('Invalid native PNG signature');
for(let off=8;off<reference.length;){const n=reference.readUInt32BE(off),type=reference.toString('ascii',off+4,off+8);if(off+12+n>reference.length)throw new Error('Truncated reference PNG');if(type==='IHDR'){width=reference.readUInt32BE(off+8);height=reference.readUInt32BE(off+12);}if(type==='tEXt'){const t=reference.toString('utf8',off+8,off+8+n);if(t.startsWith('parameters\0'))parameters=t.slice(11);}off+=12+n;}
if(width!==targetWidth||height!==targetHeight||parameters!==expectedParameters)throw new Error('Native reference dimensions/request metadata differ');
console.log('Native PNG SHA256 '+createHash('sha256').update(reference).digest('hex'));
const tokenizer='D:/AI/DiffusionForge/webui/backend/huggingface/stabilityai/stable-diffusion-xl-base-1.0/tokenizer';
const evidence=JSON.parse(readFileSync(evidencePath,'utf8'));
if(samplerId!==0&&(evidence.sampler!==samplerId||evidence.samplerName!==sampler))throw Error('Native reference sampler differs');
const hashFile=async path=>{const h=createHash('sha256');for await(const b of createReadStream(path))h.update(b);return h.digest('hex');};
const sameHash=(actual,recorded)=>typeof recorded==='string'&&actual===recorded.toLowerCase();
if(evidence.generatedSourceSha256){
  if(evidence.width!==targetWidth||evidence.height!==targetHeight||!sameHash(await hashFile(join(dirname(evidencePath),'reference.codex')),evidence.generatedSourceSha256))throw Error('Native specialized source or requested size differs');
}else if(size!=='1024x1024'||samplerId!==0)throw Error('Reference lacks specialized size/sampler source evidence');
if(evidence.nativeExit!==0||!new RegExp("^png "+size+": [0-9]+ bytes$").test(evidence.nativeResult)||!sameHash(checkpointSha256,evidence.checkpointSha256)||!sameHash(createHash('sha256').update(reference).digest('hex'),evidence.imageSha256)||!sameHash(await hashFile(join(tokenizer,'vocab.json')),evidence.vocabSha256)||!sameHash(await hashFile(join(tokenizer,'merges.txt')),evidence.mergesSha256)||!sameHash(await hashFile(join(dirname(evidencePath),'reference.cdx')),evidence.nativeCdxSha256)||!sameHash(await hashFile(join(repo,'build/sdxl-browser-reference.codex')),evidence.nativeSourceSha256))throw new Error('Native reference provenance differs');
const html=readFileSync(htmlPath,'utf8');
console.log('Studio SHA256 '+createHash('sha256').update(html).digest('hex'));
const work=mkdtempSync(join(tmpdir(),'studio-sdxl-')),pause=ms=>new Promise(r=>setTimeout(r,ms));
let server,edge,socket,gpuMonitor;const gpuSamples=[];
const sampleGpu=()=>{const r=spawnSync('nvidia-smi',['--query-gpu=memory.used,utilization.gpu','--format=csv,noheader,nounits'],{encoding:'utf8',windowsHide:true});if(r.status===0){const [usedMiB,utilization]=r.stdout.trim().split(',').map(Number);if(Number.isFinite(usedMiB)&&Number.isFinite(utilization))gpuSamples.push({ms:performance.now(),usedMiB,utilization});}};
try{
  sampleGpu();gpuMonitor=setInterval(sampleGpu,2000);
  server=http.createServer((q,r)=>{r.writeHead(200,{'Content-Type':'text/html'});r.end(html);});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  edge=spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--remote-debugging-port=0',`--user-data-dir=${join(work,'profile')}`,'--enable-unsafe-webgpu','--no-first-run','about:blank'],{stdio:'ignore'});
  console.log(`SDXL image browser PID ${edge.pid}; evidence ${work}`);
  let target;
  for(let i=0;i<120&&!target;i++){try{const port=readFileSync(join(work,'profile/DevToolsActivePort'),'utf8').split('\n')[0];target=(await(await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(t=>t.type==='page');}catch{}if(!target)await pause(250);}
  if(!target)throw new Error('Browser startup timed out');
  socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.addEventListener('open',r);socket.addEventListener('error',j);});
  const pending=new Map(),errors=[];let sequence=0;
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP timeout ${method}`));},120000);pending.set(id,reply=>{clearTimeout(timer);reply.error||reply.result?.exceptionDetails?reject(new Error(JSON.stringify(reply.error||reply.result.exceptionDetails))):resolve(reply.result);});socket.send(JSON.stringify({id,method,params}));});
  socket.addEventListener('message',event=>{const r=JSON.parse(event.data);if(pending.has(r.id)){pending.get(r.id)(r);pending.delete(r.id);}if(r.method==='Runtime.exceptionThrown')errors.push(JSON.stringify(r.params));if(r.method==='Page.fileChooserOpened')send('DOM.setFileInputFiles',{files:[dirname(ckpt)],backendNodeId:r.params.backendNodeId}).catch(e=>errors.push(String(e)));});
  for(const d of ['Page','DOM','Runtime'])await send(`${d}.enable`);
  await send('Page.setInterceptFileChooserDialog',{enabled:true});
  const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true})).result?.value;
  const wait=async expression=>{let last='';for(let i=0;i<4800;i++){if(errors.length)throw new Error(errors.join('\n'));const s=await evaluate(`({ok:(${expression}),error:typeof _st==='undefined'?'':String(_st.error||''),case:typeof _st==='undefined'?null:String(_st.phase||'')+':'+String(_st.progress||0)})`);if(s.error)throw new Error(s.error);if(s.ok)return;if(s.case!==last){console.log('progress '+s.case);last=s.case;}await pause(250);}throw new Error('SDXL image timed out');};
  await send('Page.navigate',{url:`http://127.0.0.1:${server.address().port}/`});
  await wait("typeof _st!=='undefined' && Number(_st.ready)===1");
  const defaults=await evaluate(`({size:document.getElementById('image-size').value,cfg:document.getElementById('cfg').value,sizes:[...document.getElementById('image-size').options].map(o=>o.value),dpm:document.getElementById('image-dpm').disabled,sampler:document.getElementById('image-sampler').value,enabled:[...document.getElementById('image-sampler').options].filter(o=>!o.disabled).map(o=>o.value)})`);
  if(defaults.size!=='512x512'||defaults.cfg!=='7'||JSON.stringify(defaults.sizes)!=='["512x512","768x512","512x768"]'||!defaults.dpm||defaults.sampler!=='Euler'||JSON.stringify(defaults.enabled)!=='["Euler"]')throw Error('SD1.5 family defaults differ');
  await evaluate(`window.__studioWorkers={made:0,stopped:0};const BaseWorker=Worker;window.Worker=class extends BaseWorker{constructor(...args){super(...args);__studioWorkers.made++;}terminate(){__studioWorkers.stopped++;return super.terminate();}};1`);
  const embedded=await evaluate(`Promise.all(['vocab','merges'].map(async k=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(JSON.parse(__DATA[k]))))).map(b=>b.toString(16).padStart(2,'0')).join('')))`);
  if(embedded[0]!==evidence.vocabSha256||embedded[1]!==evidence.mergesSha256)throw Error('Packaged tokenizer differs from reference');
  await evaluate(`document.getElementById('models-pick').click();1`);
  await wait(`document.getElementById('log').textContent.includes('supported checkpoints')`);
  const model=await evaluate(`[...document.querySelectorAll('#models > div')].find(e=>e.dataset.family==='sdxl checkpoint'&&e.textContent.startsWith('diffusion-models/dreamshaperXL_lightningDPMSDE.safetensors'))?.id`);
  if(!model)throw Error('SDXL checkpoint is not selectable');
  const started=performance.now();
  await evaluate(`document.getElementById(${JSON.stringify(model)}).click();1`);
  await wait(`Number(_st.loaded)===1||(!Number(_st['image-loading'])&&document.getElementById('log').textContent.includes('refused:'))`);
  if(await evaluate('Number(_st.loaded)')!==1)throw Error(await evaluate(`document.getElementById('log').textContent`));
  const xl=await evaluate(`({size:document.getElementById('image-size').value,cfg:document.getElementById('cfg').value,steps:Number(_st.steps),sizes:[...document.getElementById('image-size').options].filter(o=>!o.disabled).map(o=>o.value),disabled:[...document.getElementById('image-size').options].filter(o=>o.disabled).map(o=>o.textContent),dpm:document.getElementById('image-dpm').disabled,sampling:document.getElementById('image-sampling').textContent})`);
  if(xl.size!=='1024x1024'||xl.cfg!=='5'||xl.steps!==12||JSON.stringify(xl.sizes)!=='["1024x1024","1024x768","768x1024","1344x768","768x1344"]'||xl.disabled.length!==0||xl.dpm||!xl.sampling.includes('Karras'))throw Error('SDXL family defaults/capabilities differ: '+JSON.stringify(xl));
  const choices=await evaluate(`[...document.getElementById('image-sampler').options].filter(o=>!o.disabled).map(o=>o.value)`);
  if(JSON.stringify(choices)!==JSON.stringify(Object.keys(samplerIds)))throw Error('SDXL sampler choices differ: '+JSON.stringify(choices));
  if(!await evaluate(`typeof __DATA['sdxl-noise']==='string'&&__DATA['sdxl-noise'].length>0`))throw Error('SDE worker module is not packaged');
  console.log('PASS family defaults, supported SDXL sampler choices and packaged noise module');
  await evaluate(`(async()=>{const root=await navigator.storage.getDirectory();window.project=await root.getDirectoryHandle('StudioXL',{create:true});const w=await(await project.getFileHandle('ArtPrompts.txt',{create:true})).createWritable();await w.write(${JSON.stringify(promptFile)});await w.close();window.projectPicks=0;window.showDirectoryPicker=async()=>{projectPicks++;return project};return true})()`);
  await evaluate(`document.getElementById('open').click();1`);await wait('Number(_st.done)===1');
  if(await evaluate('Number(_st.pcount)')!==1)throw Error('Project prompt not loaded');
  await evaluate(`(()=>{const select=document.getElementById('image-sampler');select.add(new Option('Unsupported','unsupported'));select.value='unsupported';select.dispatchEvent(new Event('input'));document.getElementById('go-all').click();return true})()`);
  if(!await evaluate(`document.getElementById('log').textContent.includes('unsupported image sampler')&&Number(_st['q-images']||0)===0&&_st['image-sampler']==='unsupported'`))throw Error('Unsupported sampler was not refused without substitution');
  await evaluate(`(()=>{const select=document.getElementById('image-sampler');select.value='Euler';select.dispatchEvent(new Event('input'));return true})()`);
  for(const [bad,reason] of [['1376x768','SDXL engine sizes'],['1344x1344','SDXL engine area']]){
    await evaluate(`(()=>{const select=document.getElementById('image-size');select.add(new Option(${JSON.stringify(bad)},${JSON.stringify(bad)}));select.value=${JSON.stringify(bad)};select.dispatchEvent(new Event('input'));document.getElementById('go-all').click();return true})()`);
    if(!await evaluate(`document.getElementById('log').textContent.includes(${JSON.stringify(reason)})&&Number(_st['q-images']||0)===0&&Number(_st['image-width'])===${Number(bad.split('x')[0])}`))throw Error('Unsupported dimensions were not refused without clamping: '+bad);
  }
  await evaluate(`(()=>{const set=(id,v)=>{const el=document.getElementById(id);el.value=v;el.dispatchEvent(new Event('input'))};set('image-size',${JSON.stringify(size)});set('image-sampler',${JSON.stringify(sampler)});set('steps-in','6');set('cfg','2');set('negative',${JSON.stringify(negative)});set('runs','1');const random=random_int;random_int=(lo,hi)=>Number(hi)===2147483646?7201n:random(lo,hi);window.sampleSteps=[];const generate=browser_sdxl_sample_then__tb;browser_sdxl_sample_then__tb=(m,b,p,n,s,kind,progress,ready,refuse)=>{window.actualRequest={prompt:p,negative:n,width:Number(s.bs_width),height:Number(s.bs_height),steps:Number(s.bs_steps),cfg:s.bs_cfg,seed:Number(s.bs_seed),sampler:Number(kind)};return generate(m,b,p,n,s,kind,(phase,current,total)=>{_st.phase=phase;_st.progress=current;if(phase==='sampling'&&current>0)sampleSteps.push(Number(current));return progress(phase,current,total)},ready,refuse)};document.getElementById('go-all').click();document.getElementById('image-unload').click();document.getElementById('open').click();set('image-size',${JSON.stringify(size==='1024x768'?'1024x1024':'1024x768')});set('image-sampler',${JSON.stringify(sampler==='Euler'?'DPM++ 2M':'Euler')});set('steps-in','3');set('cfg','9');set('negative','changed during generation');return true})()`);
  if(!await evaluate('Number(_st.loaded)===1&&projectPicks===1'))throw Error('Busy model/project guards failed');
  if(!await evaluate(`_st['image-sampler']===${JSON.stringify(sampler==='Euler'?'DPM++ 2M':'Euler')}&&document.getElementById('image-sampler').value===_st['image-sampler']`))throw Error('Mid-job sampler change did not reach live controls');
  await wait(`Number(_st['q-busy'])===0&&Number(_st['q-done'])===1`);
  if(!await evaluate(`Number(_st['q-saved'])===1&&Number(_st['q-images'])===1`))throw Error(await evaluate(`document.getElementById('log').textContent`));
  const request=await evaluate('actualRequest');
  if(JSON.stringify(request)!==JSON.stringify({prompt,negative,width:targetWidth,height:targetHeight,steps:6,cfg:2,seed:7201,sampler:samplerId})||JSON.stringify(await evaluate('sampleSteps'))!=='[1,2,3,4,5,6]')throw Error('Actual engine request/progress differs: '+JSON.stringify(request));
  const saved=await evaluate(`(async()=>{const d=await project.getDirectoryHandle('Concept');const records=JSON.parse(await(await(await d.getFileHandle('catalog.json')).getFile()).text());const rec=records[0];let directory=project;const parts=rec.filePath.split('/');for(const p of parts.slice(0,-1))directory=await directory.getDirectoryHandle(p);const file=await(await directory.getFileHandle(parts.at(-1))).getFile();return {records,bytes:Array.from(new Uint8Array(await file.arrayBuffer()))}})()`);
  const rec=saved.records[0],tag=size+'_s6_cfg2_'+sampler.replace('++ ','pp').replaceAll(' ','-')+'_Karras_seed-1';
  if(saved.records.length!==1||rec.seed!==7201||rec.sourceWidth!==targetWidth||rec.sourceHeight!==targetHeight||rec.settingsTag!==tag||rec.modelFamily!=='sdxl checkpoint'||!rec.modelFile.endsWith('dreamshaperXL_lightningDPMSDE.safetensors')||rec.negativePrompt!==negative||rec.promptText!==prompt||rec.promptNumber!==1||rec.title!=='Storage'||rec.filePath!=='Concept/'+tag+'/prompt_01_storage.png')throw Error('Saved request metadata differs: '+JSON.stringify(rec));
  writeFileSync(outPath,Buffer.from(saved.bytes));
  const png=await evaluate("document.querySelector('#q0').toDataURL('image/png').split(',')[1]");
  const pixelHash=await evaluate(`(async()=>{const canvas=document.getElementById('q0');const pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',pixels))].map(x=>x.toString(16).padStart(2,'0')).join('')})()`);
  if(!Buffer.from(saved.bytes).equals(Buffer.from(png,'base64')))throw Error('Saved PNG differs from displayed canvas');
  const display=await evaluate(`(()=>{const r=document.getElementById('q0').getBoundingClientRect();return {width:r.width,height:r.height}})()`);
  if(!(display.width>0&&display.height>0&&Math.abs(display.width/display.height-targetWidth/targetHeight)<0.01))throw Error('Preview display distorts image aspect: '+JSON.stringify(display));
  console.log('PASS actual request, settings snapshot, project PNG and catalog: '+JSON.stringify(rec));
  const workers=await evaluate(`({live:_noiseJobs.size,...__studioWorkers})`);
  if(workers.live!==0||workers.made!==workers.stopped||([1,3,4,6].includes(samplerId)&&workers.made!==1))throw Error('Noise worker lifetime differs: '+JSON.stringify(workers));
  console.log('PASS noise worker lifetime: '+JSON.stringify(workers));
  const refUrl='data:image/png;base64,'+reference.toString('base64');
  const compare=await evaluate(`new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const out=document.querySelector('#q0');if(image.width!==${targetWidth}||image.height!==${targetHeight}||out.width!==${targetWidth}||out.height!==${targetHeight}){reject(new Error('Rendered dimensions differ'));return;}const a=ctx.getImageData(0,0,${targetWidth},${targetHeight}).data,b=out.getContext('2d').getImageData(0,0,${targetWidth},${targetHeight}).data;let sum=0,max=0,within8=0,n=0;for(let i=0;i<a.length;i++){if(i%4===3)continue;const d=Math.abs(a[i]-b[i]);sum+=d;max=Math.max(max,d);if(d<=8)within8++;n++;}resolve({mean:sum/n,max,within8:within8/n,count:n});};image.onerror=()=>reject(new Error('Native PNG did not decode'));image.src=${JSON.stringify(refUrl)};})`);
  console.log(JSON.stringify({comparison:compare,output:outPath,sha256:createHash('sha256').update(Buffer.from(png,'base64')).digest('hex')}));
  if(compare.count!==3*targetWidth*targetHeight||!(compare.mean<4))throw new Error('SDXL exceeds the existing txt2img mean<4/255 native-render grade');
  await evaluate(`document.getElementById('image-unload').click();1`);
  if(!await evaluate(`Number(_st.loaded)===0&&_gb.filter(Boolean).length===0`))throw Error('Image unload leaves active handles');
  await evaluate(`document.getElementById('open').click();1`);await wait(`Number(_st.done)===1&&document.getElementById('t0')?.naturalWidth===${targetWidth}&&document.getElementById('t0')?.naturalHeight===${targetHeight}`);
  const reopened=await evaluate(`(async()=>{const image=document.getElementById('t0');const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data;return {record:JSON.parse(_st['cat-json'])[0],hash:[...new Uint8Array(await crypto.subtle.digest('SHA-256',pixels))].map(x=>x.toString(16).padStart(2,'0')).join('')}})()`);
  if(reopened.hash!==pixelHash||reopened.record.id!==rec.id||reopened.record.filePath!==rec.filePath||reopened.record.settingsTag!==rec.settingsTag)throw Error('Reopened image or catalog identity differs');
  sampleGpu();console.log(JSON.stringify({loadGenerateSaveMs:performance.now()-started,sampledPeakMiB:gpuSamples.length?Math.max(...gpuSamples.map(s=>s.usedMiB)):null}));
  console.log('PASS: Studio SDXL picker/defaults, one real '+size+' image within native mean<4/255, saved PNG/catalog snapshot, reopen and unload');
}finally{
  if(gpuMonitor)clearInterval(gpuMonitor);writeFileSync(outPath+'.gpu.json',JSON.stringify(gpuSamples,null,2)+'\n');
  if(socket)socket.close();
  if(edge&&edge.exitCode===null)edge.kill();
  execFileSync('pwsh',['-NoProfile','-Command',`$ErrorActionPreference='Stop';function Owned { @(Get-CimInstance Win32_Process -Filter "Name='msedge.exe'" | Where-Object { $_.CommandLine -like '*${join(work,'profile').replace(/'/g,"''")}*' }) };foreach($p in (Owned)){Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue};for($i=0;$i -lt 20;$i++){if(@(Owned).Count -eq 0){exit 0};Start-Sleep -Milliseconds 100};throw 'Owned Edge cleanup did not finish'`],{stdio:'inherit'});
  if(server)server.close();
}
