import {readFileSync,mkdtempSync,createReadStream,writeFileSync,statSync} from 'node:fs';
import {join,resolve,dirname} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {spawn,execFileSync,spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import http from 'node:http';
import vm from 'node:vm';
const repo=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const [htmlPath,modelsArg,nativeDir,outPath]=process.argv.slice(2);
if(!outPath)throw Error('Usage: studio-lora.mjs studio.html models-dir native-dir saved.png');
const models=resolve(modelsArg);
const ckpt=join(models,'checkpoint.safetensors'),lora=join(models,'lora.safetensors');
const hash=async path=>{const h=createHash('sha256');for await(const b of createReadStream(path))h.update(b);return h.digest('hex')};
const admit=()=>{const m=JSON.parse(execFileSync('pwsh',['-NoProfile','-Command','Get-CimInstance Win32_OperatingSystem | Select-Object FreePhysicalMemory,FreeVirtualMemory | ConvertTo-Json -Compress'],{encoding:'utf8',windowsHide:true}));if(m.FreePhysicalMemory<=1572864||m.FreeVirtualMemory<=26214400)throw Error('RAM/commit admission refused');console.log('Memory '+JSON.stringify(m));};
const evidence=JSON.parse(readFileSync(join(nativeDir,'evidence.json'),'utf8'));
const family=evidence.family||'sd15',xl=family==='sdxl',size=xl?1024:512,seed=xl?7201:7,cfg=xl?2:7,weight=xl?0.6:0.75;
if(!['sd15','sdxl'].includes(family))throw Error('Unsupported reference family');
const image=evidence.images.find(x=>x.weight100===(xl?60:75)),reference=readFileSync(join(nativeDir,image.file));
if(evidence.nativeExit!==0||evidence.prompt!=='a photo of a cat'||evidence.seed!==seed||evidence.steps!==6||evidence.cfg!==cfg||evidence.width!==size||evidence.height!==size||evidence.sampler!=='Euler'||evidence.scheduler!==(xl?'Karras':'Automatic')||evidence.negative!==''||await hash(ckpt)!==evidence.checkpointSha256||await hash(lora)!==evidence.loraSha256||await hash(join(nativeDir,image.file))!==image.sha256||await hash(join(nativeDir,'reference.cdx'))!==evidence.cdxSha256||await hash(join(nativeDir,'reference.codex'))!==evidence.bundleSha256)throw Error('Native evidence mismatch');
const html=readFileSync(htmlPath,'utf8'),targetWidth=size,targetHeight=size;
console.log('Studio SHA256 '+createHash('sha256').update(html).digest('hex'));
{
const html=readFileSync(process.argv[2],'utf8');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)];
const source=scripts.at(-1)[1];
const entry=source.lastIndexOf('// Entry\ntry { opening(); } catch(e) { console.error(e); }');
if(entry<0)throw Error('Generated entry marker absent');
const context=vm.createContext({console,window:{},TextEncoder,TextDecoder,setTimeout,clearTimeout,setInterval,clearInterval,performance});
vm.runInContext(source.slice(0,entry),context);
for(const [checkpoint,lora,accepted] of [['sd15 checkpoint','sd15 LoRA',true],['sdxl checkpoint','sdxl LoRA',true],['sd15 checkpoint','sdxl LoRA',false],['sdxl checkpoint','sd15 LoRA',false],['sdxl checkpoint','flux LoRA',false],['sdxl checkpoint','ambiguous LoRA',false],['sdxl checkpoint','none',false]]){
  const reason=context.spark_image_lora_refusal(checkpoint,lora);
  if((reason==='')!==accepted||(!accepted&&!reason.includes(lora)))throw Error('LoRA family refusal differs: '+checkpoint+'/'+lora+'/'+reason);
}
const controls='tab\t CR\r unit\u001f';if(JSON.parse(context.json_quote(controls))!==controls)throw Error('Packaged JSON control fix missing');
console.log('PASS matching LoRA families, named cross-family/format refusals and packaged JSON controls');
for(const [t,v] of [['0',true],['0.75',true],['-0.5',true],['NaN',false],['Infinity',false],['1e999',false],['.',false],['',false],['0.2.3',false]]){const got=context.ss_lora_weight_valid(t);if(got!==v)throw Error(t+': '+got);console.log('PASS weight syntax '+JSON.stringify(t));}
for(const [t,v] of [['0',0],['0.75',0.75],['-0.5',-0.5]]){const got=context.ss_lora_weight__tb(t);if(got!==v)throw Error(t+': '+got);console.log('PASS parsed weight '+t);}
context.dom_get=id=>id;
context.dom_query=id=>id;
const fields={'prompt-augment':'soft light'};
context.dom_get_value=id=>fields[id]||'';
context.dom_set_value=(id,value)=>{fields[id]=value;return id};
context.dom_set_text=(id,value)=>id;
context.file_sha256_then=(file,cb)=>{if(file!=='picked-lora')throw Error('Wrong trigger file');return cb('{"sha256":"ABC123"}')};
context.fetch_get_then=(url,cb)=>{if(!url.endsWith('/api/v1/model-versions/by-hash/ABC123'))throw Error(url);return cb('{"trainedWords":["cat","painterly"]}')};
context.state_set_text('lora-file','picked-lora');context.state_set('lora-index',2n);
context.ss_trigger_find(2n,'picked-lora');
context.ss_lora_inject__tb(0n);context.ss_lora_inject__tb(0n);
if(fields['prompt-augment']!=='cat, painterly, soft light')throw Error('Trigger lookup/insertion '+fields['prompt-augment']);
context.set_timeout=fn=>fn(0n);
let request;
context.spark_image_run__tb=(...args)=>{request=args;return 0n};
context.state_set_text('loaded-lora-file','picked-lora');context.state_set_text('loaded-lora-path','lora.safetensors');context.state_set_text('loaded-lora-weight','0.75');
context.ss_image_run({}, {}, 'scene','', '7',6n,'7',()=>0n);
if(request[2]!=='scene, cat, painterly, soft light')throw Error('Trigger words did not reach engine request');
let saved;
context.file_write_then=(path,text,cb)=>{saved=JSON.parse(text);return 0n};
context.random_int=()=>1n;
context.ss_save_record(0n,7n,'tag','Concept/test.png','{"ok":true}',()=>0n);
if(saved[0].promptAugment!=='cat, painterly, soft light'||saved[0].loraTag!=='lora.safetensors:0.75')throw Error('Augment/LoRA catalog propagation');
console.log('PASS picked-file trigger lookup, duplicate-free insertion, augmented engine request and catalog propagation (I/O fixture)');
}
if(process.argv.includes('--cpu-only'))process.exit(0);
const work=mkdtempSync(join(tmpdir(),'studio-sdxl-')),pause=ms=>new Promise(r=>setTimeout(r,ms));
let server,edge,socket,gpuMonitor;const gpuSamples=[];
const sampleGpu=()=>{const r=spawnSync('nvidia-smi',['--query-gpu=memory.used,utilization.gpu','--format=csv,noheader,nounits'],{encoding:'utf8',windowsHide:true});if(r.status===0){const [usedMiB,utilization]=r.stdout.trim().split(',').map(Number);if(Number.isFinite(usedMiB)&&Number.isFinite(utilization))gpuSamples.push({ms:performance.now(),usedMiB,utilization});}};
try{
  sampleGpu();gpuMonitor=setInterval(sampleGpu,2000);
  server=http.createServer((q,r)=>{r.writeHead(200,{'Content-Type':'text/html'});r.end(html);});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  edge=spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--remote-debugging-port=0',`--user-data-dir=${join(work,'profile')}`,'--enable-unsafe-webgpu','--no-first-run','about:blank'],{stdio:'ignore'});
  console.log(`Studio LoRA image browser PID ${edge.pid}; evidence ${work}`);
  let target;
  for(let i=0;i<120&&!target;i++){try{const port=readFileSync(join(work,'profile/DevToolsActivePort'),'utf8').split('\n')[0];target=(await(await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find(t=>t.type==='page');}catch{}if(!target)await pause(250);}
  if(!target)throw new Error('Browser startup timed out');
  socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.addEventListener('open',r);socket.addEventListener('error',j);});
  const pending=new Map(),errors=[];let sequence=0;
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP timeout ${method}`));},120000);pending.set(id,reply=>{clearTimeout(timer);reply.error||reply.result?.exceptionDetails?reject(new Error(JSON.stringify(reply.error||reply.result.exceptionDetails))):resolve(reply.result);});socket.send(JSON.stringify({id,method,params}));});
  socket.addEventListener('message',event=>{const r=JSON.parse(event.data);if(pending.has(r.id)){pending.get(r.id)(r);pending.delete(r.id);}if(r.method==='Runtime.exceptionThrown')errors.push(JSON.stringify(r.params));if(r.method==='Page.fileChooserOpened')send('DOM.setFileInputFiles',{files:[dirname(ckpt)],backendNodeId:r.params.backendNodeId}).catch(e=>errors.push(String(e)));});
  for(const d of ['Page','DOM','Runtime'])await send(`${d}.enable`);
  await send('Page.setInterceptFileChooserDialog',{enabled:true});
  const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true})).result?.value;
  const wait=async expression=>{let last='';for(let i=0;i<4800;i++){if(errors.length)throw new Error(errors.join('\n'));const s=await evaluate(`({ok:(${expression}),error:typeof _st==='undefined'?'':String(_st.error||''),case:typeof _st==='undefined'?null:String(_st.phase||'')+':'+String(_st.progress||0)})`);if(s.error)throw new Error(s.error);if(s.ok)return;if(s.case!==last){console.log('progress '+s.case);last=s.case;}await pause(250);}throw new Error('Studio LoRA image timed out');};
  await send('Page.navigate',{url:`http://127.0.0.1:${server.address().port}/`});
  await wait("typeof _st!=='undefined' && Number(_st.ready)===1");

  await evaluate(`document.getElementById('models-pick').click();1`);
  await wait(`document.getElementById('log').textContent.includes('supported checkpoints')`);
  const ids=await evaluate(`({checkpoint:[...document.querySelectorAll('#models > div')].find(e=>e.dataset.family===${JSON.stringify(family)}+' checkpoint')?.id,lora:[...document.querySelectorAll('#models > div')].find(e=>e.dataset.family===${JSON.stringify(family)}+' LoRA')?.id})`);
  if(!ids.checkpoint||!ids.lora)throw Error('Picker classifications missing: '+JSON.stringify(ids));
  await evaluate(`document.getElementById('lora-use'+${JSON.stringify(ids.lora.slice(1))}).click();1`);
  const selected=await evaluate(`({file:_st['lora-file'],path:_st['lora-path']})`);
  if(!selected.file||!selected.path.endsWith('lora.safetensors'))throw Error('LoRA picker selection missing');
  const controls=await evaluate(`(()=>{const set=(id,v)=>document.getElementById(id).value=v;const before=_st['lora-file'];ss_lora_select('unsupported','bad',1n,'flux LoRA',999n);const refused=_st['lora-file']===before&&document.getElementById('log').textContent.includes('Unsupported LoRA family or format: flux LoRA');_st['tw'+_st['lora-index']]='cat, painterly';set('prompt-augment','soft light');document.getElementById('lora-inject').click();document.getElementById('lora-inject').click();const augment=document.getElementById('prompt-augment').value;set('prompt-augment','');set('lora-weight','NaN');document.getElementById(${JSON.stringify(ids.checkpoint)}).click();return {refused,augment,invalid:document.getElementById('log').textContent.includes('LoRA weight must be a finite decimal'),loaded:Number(_st.loaded||0),negative:ss_lora_weight__tb('-0.5'),valid:ss_lora_weight_valid('-0.5'),bad:ss_lora_weight_valid('1e999')}})()`);
  if(!controls.refused||controls.augment!=='cat, painterly, soft light'||!controls.invalid||controls.loaded!==0||controls.negative!==-0.5||!controls.valid||controls.bad)throw Error('LoRA controls differ: '+JSON.stringify(controls));
  console.log('PASS selected family refusal, duplicate-free trigger insertion and weight validation');
  const mismatch=await evaluate(`(()=>{const family=_st['lora-family'];_st['lora-family']=${JSON.stringify(xl?'sd15 LoRA':'sdxl LoRA')};document.getElementById(${JSON.stringify(ids.checkpoint)}).click();_st['lora-family']=family;return Number(_st.loaded||0)===0&&document.getElementById('log').textContent.includes('does not match')})()`);
  if(!mismatch)throw Error('Cross-family load did not refuse before loading');
  admit();
  const started=performance.now();
  await evaluate(`document.getElementById('lora-weight').value=${JSON.stringify(String(weight))};1`);
  if(xl)await evaluate(`const load=browser_sdxl_lora_open__tb;browser_sdxl_lora_open__tb=(checkpoint,checkpointSize,code,extra,file,size,weight,loraCode,ready,refuse)=>{window.actualLora={file,weight,size:Number(size),shader:loraCode.length,checkpointSize:Number(checkpointSize)};return load(checkpoint,checkpointSize,code,extra,file,size,weight,loraCode,ready,refuse)};1`);
  else await evaluate(`const load=browser_sd15_lora_load_then__tb;browser_sd15_lora_load_then__tb=(checkpoint,file,size,weight,code,progress,refuse,ready)=>{window.actualLora={file,weight,size:Number(size),shader:code.length};return load(checkpoint,file,size,weight,code,progress,refuse,ready)};1`);
  await evaluate(`document.getElementById(${JSON.stringify(ids.checkpoint)}).click();1`);
  await wait(`Number(_st.loaded)===1||Number(_st['image-loading'])===0`);
  if(await evaluate('Number(_st.loaded)')!==1)throw Error(await evaluate("document.getElementById('log').textContent"));
  const applied=await evaluate('actualLora');if(applied.file!==selected.file||applied.weight!==weight||applied.shader<100||applied.size!==statSync(lora).size||(xl&&applied.checkpointSize!==statSync(ckpt).size))throw Error('Actual LoRA engine call differs: '+JSON.stringify(applied));
  await evaluate(`(async()=>{const root=await navigator.storage.getDirectory();window.project=await root.getDirectoryHandle('StudioLoRA',{create:true});const w=await(await project.getFileHandle('ArtPrompts.txt',{create:true})).createWritable();await w.write(${JSON.stringify('PROMPT 01 '+String.fromCharCode(8212)+' "Cat"\n\na photo of a cat\n')});await w.close();window.showDirectoryPicker=async()=>project;return true})()`);
  await evaluate(`document.getElementById('open').click();1`);await wait('Number(_st.done)===1');
  const stale=await evaluate(`document.getElementById('lora-weight').value='0.5';document.getElementById('go-all').click();({refused:document.getElementById('log').textContent.includes('LoRA selection or weight changed'),busy:Number(_st['q-busy']||0)})`);
  if(!stale.refused||stale.busy)throw Error('Changed weight did not refuse generation');
  await evaluate(`(()=>{const set=(id,v)=>{const e=document.getElementById(id);e.value=v;e.dispatchEvent(new Event('input'))};set('lora-weight',${JSON.stringify(String(weight))});set('steps-in','6');set('cfg',${JSON.stringify(String(cfg))});set('negative','');set('runs','1');const random=random_int;random_int=(lo,hi)=>Number(hi)===2147483646?${seed}n:random(lo,hi);const run=spark_image_run__tb;spark_image_run__tb=(m,b,p,n,seed,steps,cfg,w,h,sampler,log,done)=>{window.actualRequest={prompt:p,negative:n,seed:Number(seed),steps:Number(steps),cfg,width:Number(w),height:Number(h),sampler};return run(m,b,p,n,seed,steps,cfg,w,h,sampler,log,done)};document.getElementById('go-all').click();document.getElementById('lora-none').click();set('lora-weight','-0.5');set('prompt-augment','changed during job');return true})()`);
  await wait(`Number(_st['q-busy'])===0&&Number(_st['q-done'])===1`);
  if(!await evaluate(`Number(_st['q-saved'])===1&&Number(_st['q-images'])===1`))throw Error(await evaluate(`document.getElementById('log').textContent`));
  const request=await evaluate('actualRequest');if(JSON.stringify(request)!==JSON.stringify({prompt:'a photo of a cat',negative:'',seed,steps:6,cfg,width:size,height:size,sampler:'Euler'}))throw Error('Engine request differs '+JSON.stringify(request));
  const saved=await evaluate(`(async()=>{const d=await project.getDirectoryHandle('Concept');const records=JSON.parse(await(await(await d.getFileHandle('catalog.json')).getFile()).text());const rec=records[0];let dir=project;const parts=rec.filePath.split('/');for(const p of parts.slice(0,-1))dir=await dir.getDirectoryHandle(p);const file=await(await dir.getFileHandle(parts.at(-1))).getFile();return {records,bytes:Array.from(new Uint8Array(await file.arrayBuffer()))}})()`);
  const rec=saved.records[0];if(saved.records.length!==1||rec.loraTag!==selected.path+':'+weight||rec.promptAugment!==''||rec.seed!==seed||rec.sourceWidth!==size||rec.sourceHeight!==size||rec.modelFamily!==family+' checkpoint'||rec.promptText!=='a photo of a cat')throw Error('Catalog LoRA snapshot differs '+JSON.stringify(rec));
  writeFileSync(outPath,Buffer.from(saved.bytes));
  const png=await evaluate("document.querySelector('#q0').toDataURL('image/png').split(',')[1]");
  if(!Buffer.from(saved.bytes).equals(Buffer.from(png,'base64')))throw Error('Saved PNG differs from canvas');
  const pixelHash=await evaluate(`(async()=>{const c=document.getElementById('q0');return [...new Uint8Array(await crypto.subtle.digest('SHA-256',c.getContext('2d').getImageData(0,0,${size},${size}).data))].map(x=>x.toString(16).padStart(2,'0')).join('')})()`);
  const refUrl='data:image/png;base64,'+reference.toString('base64');
  const compare=await evaluate(`new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const out=document.querySelector('#q0');if(image.width!==${targetWidth}||image.height!==${targetHeight}||out.width!==${targetWidth}||out.height!==${targetHeight}){reject(new Error('Rendered dimensions differ'));return;}const a=ctx.getImageData(0,0,${targetWidth},${targetHeight}).data,b=out.getContext('2d').getImageData(0,0,${targetWidth},${targetHeight}).data;let sum=0,max=0,within8=0,n=0;for(let i=0;i<a.length;i++){if(i%4===3)continue;const d=Math.abs(a[i]-b[i]);sum+=d;max=Math.max(max,d);if(d<=8)within8++;n++;}resolve({mean:sum/n,max,within8:within8/n,count:n});};image.onerror=()=>reject(new Error('Native PNG did not decode'));image.src=${JSON.stringify(refUrl)};})`);
  console.log(JSON.stringify({comparison:compare,output:outPath,sha256:createHash('sha256').update(Buffer.from(png,'base64')).digest('hex')}));
  if(compare.count!==3*targetWidth*targetHeight||!(compare.mean<4))throw new Error('LoRA exceeds the existing txt2img mean<4/255 native-render grade');
  const zero=evidence.images.find(x=>x.weight100===0),zeroBytes=readFileSync(join(nativeDir,zero.file));
  if(await hash(join(nativeDir,zero.file))!==zero.sha256)throw Error('Zero-weight native evidence differs');
  const zeroMean=await evaluate(`new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{if(image.width!==${size}||image.height!==${size}){reject(new Error('Zero native dimensions differ'));return;}const c=document.createElement('canvas');c.width=${size};c.height=${size};const x=c.getContext('2d');x.drawImage(image,0,0);const a=x.getImageData(0,0,${size},${size}).data,b=document.getElementById('q0').getContext('2d').getImageData(0,0,${size},${size}).data;let total=0;for(let i=0;i<a.length;i++)if(i%4!==3)total+=Math.abs(a[i]-b[i]);resolve(total/(${size}*${size}*3))};image.onerror=reject;image.src=${JSON.stringify('data:image/png;base64,'+zeroBytes.toString('base64'))}})`);
  if(!(compare.mean<zeroMean))throw Error('Weighted browser image is not closer to weighted native than zero-weight native: '+JSON.stringify({weighted:compare.mean,zeroMean}));
  if(xl&&zeroMean<4)throw Error('SDXL weighted image also passes the zero-weight native tolerance');
  console.log('PASS observable weight effect '+JSON.stringify({weighted:compare.mean,zeroMean}));
  await evaluate(`document.getElementById('image-unload').click();1`);
  if(!await evaluate(`Number(_st.loaded)===0&&_gb.filter(Boolean).length===0`))throw Error('Image unload leaves active handles');
  await evaluate(`document.getElementById('open').click();1`);await wait(`Number(_st.done)===1&&document.getElementById('t0')?.naturalWidth===${targetWidth}&&document.getElementById('t0')?.naturalHeight===${targetHeight}`);
  const reopened=await evaluate(`(async()=>{const image=document.getElementById('t0');const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data;return {record:JSON.parse(_st['cat-json'])[0],hash:[...new Uint8Array(await crypto.subtle.digest('SHA-256',pixels))].map(x=>x.toString(16).padStart(2,'0')).join('')}})()`);
  if(reopened.hash!==pixelHash||reopened.record.id!==rec.id||reopened.record.filePath!==rec.filePath||reopened.record.settingsTag!==rec.settingsTag||reopened.record.loraTag!==rec.loraTag)throw Error('Reopened image or catalog identity differs');
  if(!xl){
  admit();
  await evaluate(`document.getElementById('lora-none').click();document.getElementById('prompt-augment').value='';document.getElementById(${JSON.stringify(ids.checkpoint)}).click();1`);
  await wait(`Number(_st.loaded)===1||Number(_st['image-loading'])===0`);
  if(await evaluate('Number(_st.loaded)')!==1)throw Error(await evaluate("document.getElementById('log').textContent"));
  await evaluate(`(()=>{const set=(id,v)=>{const e=document.getElementById(id);e.value=v;e.dispatchEvent(new Event('input'))};set('prompt','a photo of a cat');set('negative','');set('seed','7');set('steps-in','6');set('cfg',${JSON.stringify(String(cfg))});document.getElementById('go').click();return true})()`);
  await wait(`Number(_st.generated)===1||(!Number(_st['image-busy'])&&document.getElementById('log').textContent.includes('generation failed'))`);
  if(await evaluate('Number(_st.generated)')!==1)throw Error('Plain-loader control failed');
  const plain=await evaluate(`new Promise((resolve,reject)=>{const image=new Image();image.onload=async()=>{const c=document.createElement('canvas');c.width=${size};c.height=${size};const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const a=ctx.getImageData(0,0,${size},${size}).data,b=document.getElementById('out').getContext('2d').getImageData(0,0,${size},${size}).data;let sum=0;for(let i=0;i<a.length;i++)if(i%4!==3)sum+=Math.abs(a[i]-b[i]);resolve({mean:sum/(${size}*${size}*3),hash:[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('')})};image.onerror=reject;image.src=${JSON.stringify('data:image/png;base64,'+zeroBytes.toString('base64'))}})`);
  if(!(plain.mean<4)||plain.hash===pixelHash)throw Error('Plain reload parity or observable LoRA effect failed: '+JSON.stringify(plain));
  await evaluate(`document.getElementById('image-unload').click();1`);
  if(!await evaluate(`Number(_st.loaded)===0&&_gb.filter(Boolean).length===0`))throw Error('Plain reload leaves active handles');
  console.log('PASS plain reload native parity and changed pixels: '+JSON.stringify(plain));
  }
  sampleGpu();console.log(JSON.stringify({suiteMs:performance.now()-started,sampledPeakMiB:gpuSamples.length?Math.max(...gpuSamples.map(s=>s.usedMiB)):null}));
  console.log('PASS: Studio '+family+' LoRA at '+weight+', native mean<4/255, saved PNG/catalog snapshot, reopen and unload');
}finally{
  if(gpuMonitor)clearInterval(gpuMonitor);writeFileSync(outPath+'.gpu.json',JSON.stringify(gpuSamples,null,2)+'\n');
  if(socket)socket.close();
  if(edge&&edge.exitCode===null)edge.kill();
  execFileSync('pwsh',['-NoProfile','-Command',`$ErrorActionPreference='Stop';function Owned { @(Get-CimInstance Win32_Process -Filter "Name='msedge.exe'" | Where-Object { $_.CommandLine -like '*${join(work,'profile').replace(/'/g,"''")}*' }) };foreach($p in (Owned)){Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue};for($i=0;$i -lt 20;$i++){if(@(Owned).Count -eq 0){exit 0};Start-Sleep -Milliseconds 100};throw 'Owned Edge cleanup did not finish'`],{stdio:'inherit'});
  if(server)server.close();
}
