param(
  [string]$ReferenceRoot = 'D:/Projects/uo-reference/UOX3',
  [string]$Output = "$PSScriptRoot/WeaponData.codex"
)
$ErrorActionPreference = 'Stop'
$weapons = "$ReferenceRoot/data/dfndata/items/gear/weapons"
$combat = "$ReferenceRoot/source/combat.cpp"

function Read-Sections([string]$path) {
  $raw = [IO.File]::ReadAllText($path)
  foreach ($m in [regex]::Matches($raw, '(?ms)^\[([^\]\r\n]+)\]\s*\{(.*?)^\}')) {
    $fields = @{}
    foreach ($line in ($m.Groups[2].Value -split "`r?`n")) {
      if ($line -match '^\s*([A-Za-z_]+)\s*=\s*(.*?)\s*$') { $fields[$Matches[1].ToLower()] = $Matches[2] }
    }
    [pscustomobject]@{ Name = $m.Groups[1].Value.Trim().ToLower(); Fields = $fields }
  }
}

# UOX3 CHandleCombat::GetWeaponType: each run of `case 0xNNNN:` ends in `return CLASS;`.
$classOf = @{}
$pending = New-Object System.Collections.Generic.List[int]
$inside = $false
foreach ($line in [IO.File]::ReadAllLines($combat)) {
  if ($line -match 'UI08 CHandleCombat::GetWeaponType\(') { $inside = $true; continue }
  if (-not $inside) { continue }
  if ($line -match '^\s*case\s+0x([0-9A-Fa-f]+)\s*:') { $pending.Add([Convert]::ToInt32($Matches[1], 16)) }
  elseif ($line -match '^\s*return\s+([A-Z_]+)\s*;') { foreach ($g in $pending) { $classOf[$g] = $Matches[1] }; $pending.Clear() }
  elseif ($line -match '^\}') { break }
}
if ($classOf.Count -lt 100) { throw "GetWeaponType parse found $($classOf.Count) graphics" }
# UOX3 CHandleCombat::GetCombatSkill, with UO skill numbers (Swordsmanship 40, Mace Fighting 41, Fencing 42, Archery 31, Wrestling 43).
$skillOf = @{ DEF_SWORDS=40; SLASH_SWORDS=40; ONEHND_LG_SWORDS=40; TWOHND_LG_SWORDS=40; ONEHND_AXES=40; TWOHND_AXES=40; BARDICHE=40; DUAL_SWORD=40
  DEF_MACES=41; LG_MACES=41; DEF_FENCING=42; TWOHND_FENCING=42; DUAL_FENCING_SLASH=42; DUAL_FENCING_STAB=42; BOWS=31; XBOWS=31; BLOWGUNS=31; THROWN=0; WRESTLING=43 }

$t2a = @{}
foreach ($file in Get-ChildItem "$weapons/weapons_t2a" -Filter '*.dfn' | Sort-Object Name) {
  foreach ($s in Read-Sections $file.FullName) {
    if ($s.Name -notmatch '^0x([0-9a-f]+)_t2a$') { continue }
    $g = [Convert]::ToInt32($Matches[1], 16)
    $d = @($s.Fields['damage'] -split '\s+' | Where-Object { $_ -ne '' } | ForEach-Object { [int]$_ })
    if ($d.Count -lt 1 -or -not $s.Fields.ContainsKey('spd')) { continue }
    $t2a[$g] = [pscustomobject]@{ Low = $d[0]; High = $(if ($d.Count -gt 1) { $d[1] } else { $d[0] }); Speed = [int]$s.Fields['spd']; Str = $(if ($s.Fields.ContainsKey('str')) { [int]$s.Fields['str'] } else { 0 }) }
  }
}
# A facing twin, `[0xGGGG] get=0xHHHH`, takes its base graphic's stats.
$rows = @{}
foreach ($g in $t2a.Keys) { $rows[$g] = $t2a[$g] }
foreach ($file in Get-ChildItem $weapons -Filter '*.dfn' | Sort-Object Name) {
  foreach ($s in Read-Sections $file.FullName) {
    if ($s.Name -notmatch '^0x([0-9a-f]+)$' -or -not $s.Fields.ContainsKey('get')) { continue }
    $g = [Convert]::ToInt32($Matches[1], 16)
    if ($s.Fields['get'] -match '^0x([0-9a-fA-F]+)$') {
      $base = [Convert]::ToInt32($Matches[1], 16)
      if ($t2a.ContainsKey($base) -and -not $rows.ContainsKey($g)) { $rows[$g] = $t2a[$base] }
    }
  }
}
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('Chapter: WeaponData')
$lines.Add('')
$lines.Add(' Modified UOX3 weapon data and CHandleCombat weapon classes, GPL-2.0-or-later.')
$lines.Add(' Copyright 1997, 98 Marcus Rating (Cironian); see the retained UOX3 license. License: ports/UOX3-LICENSE.txt.')
$lines.Add(' Generated by import-weapons.ps1 from UOX3 data/dfndata/items/gear/weapons/weapons_t2a (damage, spd, str) and')
$lines.Add(' source/combat.cpp GetWeaponType and GetCombatSkill. A weapon answers low + 256 * high + 65536 * speed')
$lines.Add(' + 16777216 * strength + 4294967296 * skill; 0 is a graphic that is not a weapon.')
$lines.Add('  wpn-stats : Integer -> Integer')
$first = $true
$count = 0
foreach ($g in ($rows.Keys | Sort-Object)) {
  $class = if ($classOf.ContainsKey($g)) { $classOf[$g] } else { 'WRESTLING' }
  $skill = $skillOf[$class]
  $r = $rows[$g]
  if ($r.Low -lt 0 -or $r.High -gt 255 -or $r.Speed -gt 255 -or $r.Str -gt 255) { throw "weapon $g out of packing range" }
  $packed = [int64]$r.Low + 256L * $r.High + 65536L * $r.Speed + 16777216L * $r.Str + 4294967296L * $skill
  $lead = if ($first) { '  wpn-stats (graphic) = if' } else { '    else if' }
  $lines.Add(('{0} graphic == {1} then {2}' -f $lead, $g, $packed))
  $first = $false
  $count++
}
$lines.Add('    else 0')
$lines.Add('  wpn-low : Integer -> Integer')
$lines.Add('  wpn-low (w) = int-mod w 256')
$lines.Add('  wpn-high : Integer -> Integer')
$lines.Add('  wpn-high (w) = int-mod (w / 256) 256')
$lines.Add('  wpn-speed : Integer -> Integer')
$lines.Add('  wpn-speed (w) = int-mod (w / 65536) 256')
$lines.Add('  wpn-strength : Integer -> Integer')
$lines.Add('  wpn-strength (w) = int-mod (w / 16777216) 256')
$lines.Add('  wpn-skill : Integer -> Integer')
$lines.Add('  wpn-skill (w) = w / 4294967296')
[IO.File]::WriteAllText($Output, (($lines -join "`r`n") + "`r`n"))
"wrote $count weapon graphics to $Output"
