param(
    [string]$ServUoRoot = 'D:/Projects/uo-reference/ServUO',
    [string]$Output = "$PSScriptRoot/TeleporterData.codex"
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# ServUO Data/teleporters.csv: X,Y,Z,Map,DestX,DestY,DestZ,DestMap,Back. GenTeleporter.CreateTeleporter places one
# teleporter at the source unless a tile already holds one, and with Back a second at the destination leading back.
# Only Felucca rows to Felucca are kept, and none with an end in the Lost Lands (x 5120 and up, y 2304 and up) or past
# the 1.25 map's 6144 x 4096, which it does not hold.
$csv = Join-Path $ServUoRoot 'Data/teleporters.csv'
$seen = @{}
$rows = [Collections.Generic.List[object]]::new()
function Lost([int]$x, [int]$y) { ($x -ge 5120 -and $y -ge 2304) -or $x -ge 6144 -or $y -ge 4096 }
function Place([int]$x, [int]$y, [int]$z, [int]$dx, [int]$dy, [int]$dz) {
    $key = "$x,$y"
    if ($seen.ContainsKey($key)) { return }
    $seen[$key] = $true
    if ((Lost $x $y) -or (Lost $dx $dy)) { return }
    $rows.Add([pscustomobject]@{ x = $x; y = $y; z = $z; dx = $dx; dy = $dy; dz = $dz })
}
foreach ($line in Get-Content -LiteralPath $csv) {
    if (-not $line -or $line.StartsWith('#')) { continue }
    $p = $line.Split(',')
    if ($p.Count -ne 9) { throw "teleporters.csv row: $line" }
    if ($p[3] -ne 'Felucca' -or $p[7] -ne 'Felucca') { continue }
    Place ([int]$p[0]) ([int]$p[1]) ([int]$p[2]) ([int]$p[4]) ([int]$p[5]) ([int]$p[6])
    if ($p[8] -eq 'True') { Place ([int]$p[4]) ([int]$p[5]) ([int]$p[6]) ([int]$p[0]) ([int]$p[1]) ([int]$p[2]) }
}
$sorted = @($rows | Sort-Object { $_.x * 4096 + $_.y })
if ($sorted.Count -lt 1) { throw 'no teleporters' }
$out = [Collections.Generic.List[string]]::new()
$out.Add('Chapter: TeleporterData')
$out.Add('')
$out.Add(' Generated by import-teleporters.ps1 from ServUO Data/teleporters.csv (GPL-2.0); do not edit by hand. Six integers a')
$out.Add(' teleporter: x, y, z, then the destination x, y, z; sorted by x * 4096 + y.')
$out.Add("  tpd-count : Integer = $($sorted.Count)")
$out.Add('  tpd-rows : Integer -> List Integer')
$cells = [Collections.Generic.List[string]]::new()
foreach ($r in $sorted) { $cells.Add("$($r.x), $($r.y), $($r.z), $($r.dx), $($r.dy), $($r.dz)") }
$body = [Collections.Generic.List[string]]::new()
for ($i = 0; $i -lt $cells.Count; $i += 8) {
    $end = [Math]::Min($i + 8, $cells.Count) - 1
    $body.Add('    ' + (($cells[$i..$end]) -join ', ') + $(if ($end -lt $cells.Count - 1) { ',' } else { ']' }))
}
$body[0] = '  tpd-rows (unused) = [' + $body[0].TrimStart()
foreach ($b in $body) { $out.Add($b) }
[IO.File]::WriteAllText($Output, (($out -join "`r`n") + "`r`n"))
"teleporters=$($sorted.Count) -> $Output"
