using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.JavaScript;

public sealed class JavaScriptEmitter : IRExprTextEmitter, ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;

    public string TargetName => "JavaScript";
    public string FileExtension => ".js";

    public string Emit(IRChapter module)
    {
        m_constructorNames = module.CollectConstructorNames();
        m_definitionArity = ValueMap<string, int>.s_empty;
        foreach (IRDefinition d in module.Definitions)
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);

        StringBuilder sb = new();
        sb.AppendLine("// Generated by Codex compiler — JavaScript backend");
        sb.AppendLine("\"use strict\";");
        sb.AppendLine();

        EmitTypeDefinitions(sb, module);

        foreach (IRDefinition def in module.Definitions)
        {
            EmitDefinition(sb, def);
            sb.AppendLine();
        }

        IRDefinition? mainDef = module.FindEntryPoint();

        if (mainDef is not null && mainDef.Parameters.Length == 0)
        {
            if (mainDef.IsEffectfulDefinition())
            {
                sb.AppendLine($"{Sanitize(Names.OpeningEntryPoint)}();");
            }
            else
            {
                sb.AppendLine($"console.log({Sanitize(Names.OpeningEntryPoint)}());");
            }
        }
        else if (module.Definitions.Length == 0)
        {
            sb.AppendLine("console.log(\"All proofs verified at compile time.\");");
        }

        return sb.ToString();
    }

    static void EmitTypeDefinitions(StringBuilder sb, IRChapter module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    EmitSumType(sb, sum);
                    break;
                case RecordType rec:
                    EmitRecordType(sb, rec);
                    break;
            }
        }
    }

    static void EmitSumType(StringBuilder sb, SumType sum)
    {
        foreach (SumConstructorType ctor in sum.Constructors)
        {
            string name = Sanitize(ctor.Name.Value);
            if (ctor.Fields.IsEmpty)
            {
                sb.AppendLine(
                    $"function {name}() " +
                    $"{{ return Object.freeze({{ tag: \"{ctor.Name.Value}\" }}); }}");
            }
            else
            {
                StringBuilder paramList = new();
                StringBuilder fieldList = new();
                for (int i = 0; i < ctor.Fields.Length; i++)
                {
                    if (i > 0) { paramList.Append(", "); fieldList.Append(", "); }
                    paramList.Append($"field{i}");
                    fieldList.Append($"field{i}: field{i}");
                }
                sb.AppendLine(
                    $"function {name}({paramList}) " +
                    $"{{ return Object.freeze({{ tag: \"{ctor.Name.Value}\", {fieldList} }}); }}");
            }
        }
        sb.AppendLine();
    }

    static void EmitRecordType(StringBuilder sb, RecordType rec)
    {
        string name = Sanitize(rec.TypeName.Value);
        StringBuilder paramList = new();
        StringBuilder fieldList = new();
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            string fieldName = Sanitize(rec.Fields[i].FieldName.Value);
            if (i > 0) { paramList.Append(", "); fieldList.Append(", "); }
            paramList.Append(fieldName);
            fieldList.Append($"{fieldName}: {fieldName}");
        }
        sb.AppendLine(
            $"function {name}({paramList}) " +
            $"{{ return Object.freeze({{ {fieldList} }}); }}");
        sb.AppendLine();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        if (HasSelfTailCall(def))
        {
            EmitTailCallDefinition(sb, def);
            return;
        }

        string name = Sanitize(def.Name);
        sb.Append($"function {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(Sanitize(def.Parameters[i].Name));
        }
        sb.AppendLine(") {");

        if (def.IsEffectfulDefinition())
        {
            sb.Append("    ");
            EmitExpr(sb, def.Body, 1);
            sb.AppendLine(";");
        }
        else
        {
            sb.Append("    return ");
            EmitExpr(sb, def.Body, 1);
            sb.AppendLine(";");
        }

        sb.AppendLine("}");
    }

    static bool HasSelfTailCall(IRDefinition def)
    {
        if (def.Parameters.Length == 0)
            return false;
        return def.Body.HasTailCall(def.Name);
    }

    void EmitTailCallDefinition(StringBuilder sb, IRDefinition def)
    {
        string name = Sanitize(def.Name);
        sb.Append($"function {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(Sanitize(def.Parameters[i].Name));
        }
        sb.AppendLine(") {");
        sb.AppendLine("    while (true) {");

        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, 2);

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 4);

        switch (expr)
        {
            case IRIf iff:
                sb.Append($"{pad}if (");
                EmitExpr(sb, iff.Condition, indent);
                sb.AppendLine(") {");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}} else {{");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}}");
                break;

            case IRLet let:
                sb.Append($"{pad}const {Sanitize(let.Name)} = ");
                EmitExpr(sb, let.Value, indent);
                sb.AppendLine(";");
                EmitTailCallBody(sb, let.Body, funcName, parameters, indent);
                break;

            case IRApply app when app.IsSelfCall(funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    sb.Append($"{pad}const _tco_{i} = ");
                    EmitExpr(sb, args[i], indent);
                    sb.AppendLine(";");
                }
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                    sb.AppendLine($"{pad}{Sanitize(parameters[i].Name)} = _tco_{i};");
                sb.AppendLine($"{pad}continue;");
                break;
            }

            default:
                sb.Append($"{pad}return ");
                EmitExpr(sb, expr, indent);
                sb.AppendLine(";");
                break;
        }
    }

    protected override void EmitFuelExhaustedToken(StringBuilder sb) => sb.Append("undefined");

    protected override void EmitUnhandled(StringBuilder sb, IRExpr expr, int indent) => sb.Append("undefined");

    protected override void EmitIntegerLit(StringBuilder sb, IRIntegerLit lit, int indent) =>
        sb.Append($"{lit.Value}n");

    protected override void EmitNumberLit(StringBuilder sb, IRNumberLit lit, int indent) =>
        sb.Append($"{lit.Value}");

    protected override void EmitTextLit(StringBuilder sb, IRTextLit lit, int indent) =>
        sb.Append($"\"{EscapeString(lit.Value)}\"");

    protected override void EmitBoolLit(StringBuilder sb, IRBoolLit lit, int indent) =>
        sb.Append(lit.Value ? "true" : "false");

    protected override void EmitName(StringBuilder sb, IRName name, int indent)
    {
        if (name.Name == "read-line")
        {
            sb.Append("(require('readline-sync').question(''))");
        }
        else if (name.Name == "show")
        {
            sb.Append("String");
        }
        else if (name.Name == "negate")
        {
            sb.Append("((x) => -x)");
        }
        else if (name.Name.Length > 0 && char.IsUpper(name.Name[0])
            && name.Type is not FunctionType)
        {
            sb.Append($"{Sanitize(name.Name)}()");
        }
        else if (m_definitionArity.TryGet(name.Name, out int nameArity)
            && nameArity == 0
            && name.Type is not FunctionType)
        {
            sb.Append($"{Sanitize(name.Name)}()");
        }
        else
        {
            sb.Append(Sanitize(name.Name));
        }
    }

    protected override void EmitNegate(StringBuilder sb, IRNegate neg, int indent)
    {
        sb.Append("(-");
        EmitExpr(sb, neg.Operand, indent);
        sb.Append(')');
    }

    protected override void EmitIf(StringBuilder sb, IRIf iff, int indent)
    {
        sb.Append('(');
        EmitExpr(sb, iff.Condition, indent);
        sb.Append(" ? ");
        EmitExpr(sb, iff.Then, indent);
        sb.Append(" : ");
        EmitExpr(sb, iff.Else, indent);
        sb.Append(')');
    }

    protected override void EmitList(StringBuilder sb, IRList list, int indent)
    {
        sb.Append('[');
        for (int i = 0; i < list.Elements.Length; i++)
        {
            if (i > 0)
                sb.Append(", ");

            EmitExpr(sb, list.Elements[i], indent);
        }
        sb.Append(']');
    }

    protected override void EmitAct(StringBuilder sb, IRAct act, int indent) => EmitActExpr(sb, act, indent);

    protected override void EmitRecord(StringBuilder sb, IRRecord rec, int indent)
    {
        sb.Append($"{Sanitize(rec.TypeName)}(");
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            if (i > 0)
                sb.Append(", ");

            EmitExpr(sb, rec.Fields[i].Value, indent);
        }
        sb.Append(')');
    }

    protected override void EmitFieldAccess(StringBuilder sb, IRFieldAccess fa, int indent)
    {
        EmitExpr(sb, fa.Record, indent);
        sb.Append('.');
        sb.Append(Sanitize(fa.FieldName));
    }

    protected override void EmitError(StringBuilder sb, IRError err, int indent) =>
        sb.Append($"(() => {{ throw new Error(\"{EscapeString(err.Message)}\"); }})()");

    protected override void EmitApply(StringBuilder sb, IRApply app, int indent)
    {
        if (app.Function is IRName fn && fn.Name == "show")
        {
            sb.Append("String(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn2 && fn2.Name == "negate")
        {
            sb.Append("(-");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn3 && fn3.Name == "print-line")
        {
            sb.Append("console.log(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn4 && fn4.Name == "open-file")
        {
            sb.Append("require('fs').readFileSync(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn5 && fn5.Name == "read-all")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".toString()");
        }
        else if (app.Function is IRName fn6 && fn6.Name == "close-file")
        {
            sb.Append("undefined");
        }
        else if (app.Function is IRName fn7 && fn7.Name == "text-length")
        {
            sb.Append("BigInt(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".length)");
        }
        else if (app.Function is IRName fnCtt && fnCtt.Name == "char-to-text")
        {
            sb.Append("String.fromCharCode(Number(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))");
        }
        else if (app.Function is IRName fn8 && fn8.Name == "is-letter")
        {
            sb.Append("(/^[a-zA-Z]/.test(String.fromCharCode(Number(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))))");
        }
        else if (app.Function is IRName fn9 && fn9.Name == "is-digit")
        {
            sb.Append("(/^[0-9]/.test(String.fromCharCode(Number(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))))");
        }
        else if (app.Function is IRName fn10 && fn10.Name == "is-whitespace")
        {
            sb.Append("(/^\\s/.test(String.fromCharCode(Number(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))))");
        }
        else if (app.Function is IRName fn11 && fn11.Name == "text-to-integer")
        {
            sb.Append("parseInt(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(", 10)");
        }
        else if (app.Function is IRName fn11b && fn11b.Name == "integer-to-text")
        {
            sb.Append("String(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn12 && fn12.Name == "char-code")
        {
            // Char -> Integer: identity (both are BigInt)
            EmitExpr(sb, app.Argument, indent);
        }
        else if (app.Function is IRName fn13 && fn13.Name == "code-to-char")
        {
            // Integer -> Char: identity (both are BigInt)
            EmitExpr(sb, app.Argument, indent);
        }
        else if (app.Function is IRName fn14 && fn14.Name == "list-length")
        {
            sb.Append("BigInt(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".length)");
        }
        else if (TryEmitMultiArgBuiltin(sb, app, indent))
        {
        }
        else
        {
            string? ctorName = FindConstructorName(app);
            if (ctorName is not null)
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                sb.Append($"{Sanitize(ctorName)}(");
                for (int i = 0; i < args.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, args[i], indent);
                }
                sb.Append(')');
            }
            else
            {
                string? defName = FindDefinitionName(app);
                if (defName is not null
                    && m_definitionArity.TryGet(defName, out int arity)
                    && arity > 1)
                {
                    List<IRExpr> args = [];
                    CollectApplyArgs(app, args);
                    if (args.Count == arity)
                    {
                        sb.Append(Sanitize(defName));
                        sb.Append('(');
                        for (int i = 0; i < args.Count; i++)
                        {
                            if (i > 0) sb.Append(", ");
                            EmitExpr(sb, args[i], indent);
                        }
                        sb.Append(')');
                    }
                    else
                    {
                        EmitExpr(sb, app.Function, indent);
                        sb.Append('(');
                        EmitExpr(sb, app.Argument, indent);
                        sb.Append(')');
                    }
                }
                else
                {
                    EmitExpr(sb, app.Function, indent);
                    sb.Append('(');
                    EmitExpr(sb, app.Argument, indent);
                    sb.Append(')');
                }
            }
        }
    }

    protected override void EmitBinary(StringBuilder sb, IRBinary bin, int indent)
    {
        switch (bin.Op)
        {
            case IRBinaryOp.AppendText:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" + ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.AppendList:
                sb.Append("[...");
                EmitExpr(sb, bin.Left, indent);
                sb.Append(", ...");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(']');
                break;

            case IRBinaryOp.ConsList:
                sb.Append('[');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(", ...");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(']');
                break;

            case IRBinaryOp.PowInt:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" ** ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            default:
                string op = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
                    IRBinaryOp.DivInt or IRBinaryOp.DivNum => "/",
                    IRBinaryOp.Eq => "===",
                    IRBinaryOp.NotEq => "!==",
                    IRBinaryOp.Lt => "<",
                    IRBinaryOp.Gt => ">",
                    IRBinaryOp.LtEq => "<=",
                    IRBinaryOp.GtEq => ">=",
                    IRBinaryOp.And => "&&",
                    IRBinaryOp.Or => "||",
                    _ => "+"
                };
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append($" {op} ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;
        }
    }

    protected override void EmitLet(StringBuilder sb, IRLet let, int indent)
    {
        sb.Append("((");
        sb.Append(Sanitize(let.Name));
        sb.Append(") => ");
        EmitExpr(sb, let.Body, indent);
        sb.Append(")(");
        EmitExpr(sb, let.Value, indent);
        sb.Append(')');
    }

    protected override void EmitLambda(StringBuilder sb, IRLambda lam, int indent)
    {
        sb.Append('(');
        for (int i = 0; i < lam.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(Sanitize(lam.Parameters[i].Name));
        }
        sb.Append(") => ");
        EmitExpr(sb, lam.Body, indent);
    }

    protected override void EmitMatch(StringBuilder sb, IRMatch match, int indent)
    {
        sb.Append("((_s) => ");
        bool first = true;
        int opens = 0;
        foreach (IRMatchBranch branch in match.Branches)
        {
            switch (branch.Pattern)
            {
                case IRLiteralPattern litPat:
                    if (!first) sb.Append(" : ");
                    first = false;
                    opens++;
                    sb.Append("(_s");
                    sb.Append(litPat.Value switch
                    {
                        bool b => $" === {(b ? "true" : "false")}",
                        long l => $" === {l}n",
                        string s => $" === \"{EscapeString(s)}\"",
                        _ => $" === ${litPat.Value}"
                    });
                    sb.Append(" ? ");
                    EmitExpr(sb, branch.Body, indent);
                    break;

                case IRCtorPattern ctorPat:
                    if (!first) sb.Append(" : ");
                    first = false;
                    opens++;
                    sb.Append($"(_s.tag === \"{ctorPat.Name}\" ? ");
                    EmitCtorPatternBody(sb, ctorPat, "_s", branch.Body, indent);
                    break;

                case IRVarPattern varPat:
                    if (!first) sb.Append(" : ");
                    sb.Append("((");
                    sb.Append(Sanitize(varPat.Name));
                    sb.Append(") => ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append(")(_s)");
                    for (int i = 0; i < opens; i++) sb.Append(')');
                    sb.Append(")(");
                    EmitExpr(sb, match.Scrutinee, indent);
                    sb.Append(')');
                    return;

                case IRWildcardPattern:
                    if (!first) sb.Append(" : ");
                    EmitExpr(sb, branch.Body, indent);
                    for (int i = 0; i < opens; i++) sb.Append(')');
                    sb.Append(")(");
                    EmitExpr(sb, match.Scrutinee, indent);
                    sb.Append(')');
                    return;
            }
        }

        sb.Append(" : (() => { throw new Error(\"Non-exhaustive match\"); })()");
        for (int i = 0; i < opens; i++) sb.Append(')');
        sb.Append(")(");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.Append(')');
    }

    void EmitCtorPatternBody(
        StringBuilder sb, IRCtorPattern ctorPat, string binding,
        IRExpr body, int indent)
    {
        List<(string Name, string Access)> varBindings = [];
        for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
        {
            if (ctorPat.SubPatterns[i] is IRVarPattern vp)
            {
                varBindings.Add((vp.Name, $"{binding}.field{i}"));
            }
        }

        if (varBindings.Count == 0)
        {
            EmitExpr(sb, body, indent);
            return;
        }

        sb.Append("(() => { ");
        foreach ((string name, string access) in varBindings)
        {
            sb.Append($"const {Sanitize(name)} = {access}; ");
        }
        sb.Append("return ");
        EmitExpr(sb, body, indent);
        sb.Append("; })()");
    }

    void EmitActExpr(StringBuilder sb, IRAct actExpr, int indent)
    {
        sb.AppendLine("(() => {");
        string pad = new(' ', (indent + 1) * 4);
        foreach (IRActStatement stmt in actExpr.Statements)
        {
            switch (stmt)
            {
                case IRActBind bind:
                    sb.Append(pad);
                    sb.Append($"const {Sanitize(bind.Name)} = ");
                    EmitExpr(sb, bind.Value, indent + 1);
                    sb.AppendLine(";");
                    break;
                case IRActExec exec:
                    sb.Append(pad);
                    EmitExpr(sb, exec.Expression, indent + 1);
                    sb.AppendLine(";");
                    break;
            }
        }
        sb.Append(new string(' ', indent * 4));
        sb.Append("})()");
    }

    static string? FindConstructorName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && name.Name.Length > 0 && char.IsUpper(name.Name[0]))
            return name.Name;
        return null;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]))
            return name.Name;
        return null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner)
            CollectApplyArgs(inner, args);
        args.Add(app.Argument);
    }

    static readonly Set<string> s_multiArgBuiltins = Set<string>.Of(
        "char-at", "substring", "list-at", "text-replace",
        "fork", "await", "par", "race");

    static string? FindBuiltinRoot(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && s_multiArgBuiltins.Contains(name.Name))
            return name.Name;
        return null;
    }

    bool TryEmitMultiArgBuiltin(StringBuilder sb, IRApply app, int indent)
    {
        string? name = FindBuiltinRoot(app);
        if (name is null) return false;

        List<IRExpr> args = [];
        CollectApplyArgs(app, args);

        switch (name)
        {
            case "char-at" when args.Count == 2:
                sb.Append("BigInt(");
                EmitExpr(sb, args[0], indent);
                sb.Append(".charCodeAt(Number(");
                EmitExpr(sb, args[1], indent);
                sb.Append(")))");
                return true;

            case "substring" when args.Count == 3:
                EmitExpr(sb, args[0], indent);
                sb.Append(".substring(Number(");
                EmitExpr(sb, args[1], indent);
                sb.Append("), Number(");
                EmitExpr(sb, args[1], indent);
                sb.Append(" + ");
                EmitExpr(sb, args[2], indent);
                sb.Append("))");
                return true;

            case "list-at" when args.Count == 2:
                EmitExpr(sb, args[0], indent);
                sb.Append("[Number(");
                EmitExpr(sb, args[1], indent);
                sb.Append(")]");
                return true;

            case "text-replace" when args.Count == 3:
                EmitExpr(sb, args[0], indent);
                sb.Append(".replaceAll(");
                EmitExpr(sb, args[1], indent);
                sb.Append(", ");
                EmitExpr(sb, args[2], indent);
                sb.Append(')');
                return true;

            case "fork" when args.Count == 1:
                sb.Append("Promise.resolve().then(() => (");
                EmitExpr(sb, args[0], indent);
                sb.Append(")(null))");
                return true;

            case "await" when args.Count == 1:
                sb.Append("(await ");
                EmitExpr(sb, args[0], indent);
                sb.Append(')');
                return true;

            case "par" when args.Count == 2:
                sb.Append("await Promise.all(");
                EmitExpr(sb, args[1], indent);
                sb.Append(".map(_x_ => Promise.resolve().then(() => (");
                EmitExpr(sb, args[0], indent);
                sb.Append(")(_x_))))");
                return true;

            case "race" when args.Count == 1:
                sb.Append("await Promise.race(");
                EmitExpr(sb, args[0], indent);
                sb.Append(".map(_t_ => Promise.resolve().then(() => _t_(null))))");
                return true;

            default:
                return false;
        }
    }



    static string Sanitize(string name) =>
        NameSanitizer.Sanitize(name, s_reservedKeywords, escapePrefix: "_");

    static readonly HashSet<string> s_reservedKeywords =
    [
        "class", "function", "var", "let", "const", "return", "if",
        "else", "for", "while", "do", "switch", "case", "break",
        "continue", "new", "this", "null", "true", "false", "in",
        "of", "typeof", "instanceof", "void", "delete", "throw",
        "try", "catch", "finally", "with", "yield", "async",
        "await", "import", "export", "default", "extends", "super",
    ];

    static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
