using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Cpp;

public sealed class CppEmitter : IRExprTextEmitter, ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;
    Map<string, string> m_ctorToVariant = Map<string, string>.s_empty;

    public string TargetName => "C++";
    public string FileExtension => ".cpp";

    public string Emit(IRChapter module)
    {
        m_constructorNames = module.CollectConstructorNames();
        m_ctorToVariant = BuildCtorToVariantMap(module);
        m_definitionArity = ValueMap<string, int>.s_empty;
        foreach (IRDefinition d in module.Definitions)
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);

        StringBuilder sb = new();
        sb.AppendLine("// Generated by Codex compiler — C++ backend");
        sb.AppendLine("// Compile: g++ -std=c++17 -o output output.cpp");
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine("#include <string>");
        sb.AppendLine("#include <vector>");
        sb.AppendLine("#include <functional>");
        sb.AppendLine("#include <variant>");
        sb.AppendLine("#include <iostream>");
        sb.AppendLine("#include <cmath>");
        sb.AppendLine("#include <algorithm>");
        sb.AppendLine("#include <sstream>");
        sb.AppendLine("#include <fstream>");
        sb.AppendLine();
        sb.AppendLine("namespace codex {");
        sb.AppendLine();

        EmitForwardDeclarations(sb, module);
        EmitTypeDefinitions(sb, module);

        IRDefinition? mainDef = module.FindEntryPoint();

        foreach (IRDefinition def in module.Definitions)
        {
            if (def == mainDef)
                continue;
            EmitDefinition(sb, def);
            sb.AppendLine();
        }

        sb.AppendLine("} // namespace codex");
        sb.AppendLine();

        if (mainDef is not null)
        {
            sb.AppendLine("int main() {");
            sb.AppendLine("    using namespace codex;");
            if (mainDef.IsEffectfulDefinition())
            {
                EmitStatement(sb, mainDef.Body, 1);
            }
            else
            {
                sb.Append("    std::cout << ");
                EmitExpr(sb, mainDef.Body, 1);
                sb.AppendLine(" << std::endl;");
            }
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("int main() {");
            if (module.Definitions.Length == 0)
                sb.AppendLine("    std::cout << \"All proofs verified at compile time.\" << std::endl;");
            else
                sb.AppendLine("    std::cout << \"Chapter loaded.\" << std::endl;");
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void EmitForwardDeclarations(StringBuilder sb, IRChapter module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    foreach (SumConstructorType ctor in sum.Constructors)
                        sb.AppendLine($"struct {Sanitize(ctor.Name.Value)};");
                    break;
                case RecordType rec:
                    sb.AppendLine($"struct {Sanitize(rec.TypeName.Value)};");
                    break;
            }
        }
        sb.AppendLine();
    }

    void EmitTypeDefinitions(StringBuilder sb, IRChapter module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    EmitSumType(sb, sum);
                    break;
                case RecordType rec:
                    EmitRecordType(sb, rec);
                    break;
            }
        }
    }

    void EmitSumType(StringBuilder sb, SumType sum)
    {
        SortedSet<int> sumTvars = new();
        foreach (SumConstructorType ctor in sum.Constructors)
        {
            foreach (CodexType f in ctor.Fields)
                CollectTypeVars(f, sumTvars);
        }

        string templatePrefix = EmitTemplatePrefix(sumTvars);

        foreach (SumConstructorType ctor in sum.Constructors)
        {
            string name = Sanitize(ctor.Name.Value);
            if (templatePrefix.Length > 0)
                sb.AppendLine(templatePrefix);
            sb.AppendLine($"struct {name} {{");
            for (int i = 0; i < ctor.Fields.Length; i++)
                sb.AppendLine($"    {EmitType(ctor.Fields[i])} field{i};");
            sb.AppendLine("};");
            sb.AppendLine();
        }

        string baseName = Sanitize(sum.TypeName.Value);
        if (templatePrefix.Length > 0)
            sb.AppendLine(templatePrefix);
        sb.Append($"using {baseName} = std::variant<");
        for (int i = 0; i < sum.Constructors.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            string ctorName = Sanitize(sum.Constructors[i].Name.Value);
            if (sumTvars.Count > 0)
            {
                sb.Append($"{ctorName}<");
                bool first = true;
                foreach (int tv in sumTvars)
                {
                    if (!first) sb.Append(", ");
                    first = false;
                    sb.Append($"T{tv}");
                }
                sb.Append('>');
            }
            else
            {
                sb.Append(ctorName);
            }
        }
        sb.AppendLine(">;");
        sb.AppendLine();
    }

    static void EmitRecordType(StringBuilder sb, RecordType rec)
    {
        SortedSet<int> tvars = new();
        foreach (RecordFieldType f in rec.Fields)
            CollectTypeVars(f.Type, tvars);

        string name = Sanitize(rec.TypeName.Value);
        string templatePrefix = EmitTemplatePrefix(tvars);
        if (templatePrefix.Length > 0)
            sb.AppendLine(templatePrefix);
        sb.AppendLine($"struct {name} {{");
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            RecordFieldType field = rec.Fields[i];
            sb.AppendLine($"    {EmitType(field.Type)} {Sanitize(field.FieldName.Value)};");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        if (HasSelfTailCall(def))
        {
            EmitTailCallDefinition(sb, def);
            return;
        }

        SortedSet<int> tvars = new();
        CollectTypeVars(def.Type, tvars);
        string templatePrefix = EmitTemplatePrefix(tvars);

        string returnType = EmitReturnType(def);
        string name = Sanitize(def.Name);

        if (templatePrefix.Length > 0)
            sb.AppendLine(templatePrefix);

        if (def.Parameters.Length == 0 && !def.IsEffectfulDefinition())
        {
            sb.Append($"auto {name}()");
        }
        else
        {
            sb.Append($"{returnType} {name}(");
            for (int i = 0; i < def.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"{EmitType(def.Parameters[i].Type)} {Sanitize(def.Parameters[i].Name)}");
            }
            sb.Append(')');
        }

        sb.AppendLine(" {");
        if (def.IsEffectfulDefinition())
        {
            sb.Append("    ");
            EmitStatement(sb, def.Body, 1);
            sb.AppendLine();
        }
        else
        {
            sb.Append("    return ");
            EmitExpr(sb, def.Body, 1);
            sb.AppendLine(";");
        }
        sb.AppendLine("}");
    }

    void EmitTailCallDefinition(StringBuilder sb, IRDefinition def)
    {
        SortedSet<int> tvars = new();
        CollectTypeVars(def.Type, tvars);
        string templatePrefix = EmitTemplatePrefix(tvars);

        string returnType = EmitReturnType(def);
        string name = Sanitize(def.Name);

        if (templatePrefix.Length > 0)
            sb.AppendLine(templatePrefix);
        sb.Append($"{returnType} {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{EmitType(def.Parameters[i].Type)} {Sanitize(def.Parameters[i].Name)}");
        }
        sb.AppendLine(") {");
        sb.AppendLine("    while (true) {");

        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, 2);

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 4);

        switch (expr)
        {
            case IRIf iff:
                sb.Append($"{pad}if (");
                EmitExpr(sb, iff.Condition, indent);
                sb.AppendLine(") {");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}} else {{");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}}");
                break;

            case IRLet let:
                sb.Append($"{pad}auto {Sanitize(let.Name)} = ");
                EmitExpr(sb, let.Value, indent);
                sb.AppendLine(";");
                EmitTailCallBody(sb, let.Body, funcName, parameters, indent);
                break;

            case IRMatch match:
                EmitTailCallMatch(sb, match, funcName, parameters, indent);
                break;

            case IRApply app when app.IsSelfCall(funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    sb.Append($"{pad}auto _tco_{i} = ");
                    EmitExpr(sb, args[i], indent);
                    sb.AppendLine(";");
                }
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                    sb.AppendLine($"{pad}{Sanitize(parameters[i].Name)} = _tco_{i};");
                sb.AppendLine($"{pad}continue;");
                break;
            }

            default:
                sb.Append($"{pad}return ");
                EmitExpr(sb, expr, indent);
                sb.AppendLine(";");
                break;
        }
    }

    void EmitTailCallMatch(
        StringBuilder sb, IRMatch match, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 4);
        sb.Append($"{pad}auto _tco_s = ");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.AppendLine(";");

        bool first = true;
        int branchIdx = 0;
        foreach (IRMatchBranch branch in match.Branches)
        {
            string keyword = first ? "if" : "else if";
            first = false;
            string matchVar = $"_tco_m{branchIdx}";
            branchIdx++;

            switch (branch.Pattern)
            {
                case IRCtorPattern ctorPat:
                    sb.AppendLine(
                        $"{pad}{keyword} (auto* {matchVar} = std::get_if<{Sanitize(ctorPat.Name)}>(&_tco_s)) {{");
                    for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
                    {
                        if (ctorPat.SubPatterns[i] is IRVarPattern svp)
                            sb.AppendLine($"{pad}    auto {Sanitize(svp.Name)} = {matchVar}->field{i};");
                    }
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    break;

                case IRLiteralPattern litPat:
                    sb.Append($"{pad}{keyword} (_tco_s == ");
                    EmitLiteralValue(sb, litPat.Value);
                    sb.AppendLine(") {");
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    break;

                case IRVarPattern varPat:
                    sb.AppendLine($"{pad}{{");
                    sb.AppendLine($"{pad}    auto {Sanitize(varPat.Name)} = _tco_s;");
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    return;

                case IRWildcardPattern:
                    sb.AppendLine($"{pad}{{");
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    return;
            }
        }
    }

    protected override void EmitFuelExhaustedToken(StringBuilder sb) => sb.Append("nullptr");

    protected override void EmitUnhandled(StringBuilder sb, IRExpr expr, int indent) => sb.Append("nullptr");

    protected override void EmitIntegerLit(StringBuilder sb, IRIntegerLit lit, int indent) =>
        sb.Append($"int64_t({lit.Value})");

    protected override void EmitNumberLit(StringBuilder sb, IRNumberLit lit, int indent) =>
        sb.Append($"double({lit.Value})");

    protected override void EmitTextLit(StringBuilder sb, IRTextLit lit, int indent) =>
        sb.Append($"std::string(\"{EscapeString(lit.Value)}\")");

    protected override void EmitBoolLit(StringBuilder sb, IRBoolLit lit, int indent) =>
        sb.Append(lit.Value ? "true" : "false");

    protected override void EmitName(StringBuilder sb, IRName name, int indent)
    {
        if (name.Name == "read-line")
        {
            sb.Append("[&]{ std::string _l; std::getline(std::cin, _l); return _l; }()");
        }
        else if (name.Name == "show")
        {
            sb.Append("[](auto _x) -> std::string { std::ostringstream _o; _o << _x; return _o.str(); }");
        }
        else if (name.Name == "negate")
        {
            sb.Append("[](auto _x) { return -_x; }");
        }
        else if (name.Name == "True")
        {
            sb.Append("true");
        }
        else if (name.Name == "False")
        {
            sb.Append("false");
        }
        else if (name.Name == "Nothing")
        {
            sb.Append("nullptr");
        }
        else if (name.Name.Length > 0 && char.IsUpper(name.Name[0])
            && name.Type is not FunctionType
            && !m_constructorNames.Contains(name.Name))
        {
            sb.Append($"{Sanitize(name.Name)}()");
        }
        else if (m_constructorNames.Contains(name.Name)
            && name.Type is not FunctionType)
        {
            sb.Append($"{Sanitize(name.Name)}{{}}");
        }
        else if (m_definitionArity.TryGet(name.Name, out int nameArity)
            && nameArity == 0
            && name.Type is not FunctionType)
        {
            sb.Append($"{Sanitize(name.Name)}()");
        }
        else
        {
            sb.Append(Sanitize(name.Name));
        }
    }

    protected override void EmitNegate(StringBuilder sb, IRNegate neg, int indent)
    {
        sb.Append("(-");
        EmitExpr(sb, neg.Operand, indent);
        sb.Append(')');
    }

    protected override void EmitIf(StringBuilder sb, IRIf iff, int indent)
    {
        sb.Append('(');
        EmitExpr(sb, iff.Condition, indent);
        sb.Append(" ? ");
        EmitExpr(sb, iff.Then, indent);
        sb.Append(" : ");
        EmitExpr(sb, iff.Else, indent);
        sb.Append(')');
    }

    protected override void EmitList(StringBuilder sb, IRList list, int indent)
    {
        sb.Append($"std::vector<{EmitType(list.ElementType)}>({{");
        for (int i = 0; i < list.Elements.Length; i++)
        {
            if (i > 0)
                sb.Append(", ");

            EmitExpr(sb, list.Elements[i], indent);
        }
        sb.Append("})");
    }

    protected override void EmitAct(StringBuilder sb, IRAct act, int indent) => EmitActExpr(sb, act, indent);

    protected override void EmitRecord(StringBuilder sb, IRRecord rec, int indent)
    {
        sb.Append($"{Sanitize(rec.TypeName)}{{");
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            if (i > 0)
                sb.Append(", ");

            EmitExpr(sb, rec.Fields[i].Value, indent);
        }
        sb.Append('}');
    }

    protected override void EmitFieldAccess(StringBuilder sb, IRFieldAccess fa, int indent)
    {
        EmitExpr(sb, fa.Record, indent);
        sb.Append('.');
        sb.Append(Sanitize(fa.FieldName));
    }

    protected override void EmitError(StringBuilder sb, IRError err, int indent) =>
        sb.Append($"throw std::runtime_error(\"{EscapeString(err.Message)}\")");

    protected override void EmitApply(StringBuilder sb, IRApply app, int indent)
    {
        if (app.Function is IRName fn && fn.Name == "show")
        {
            sb.Append("[&]{ std::ostringstream _o; _o << ");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("; return _o.str(); }()");
        }
        else if (app.Function is IRName fn2 && fn2.Name == "negate")
        {
            sb.Append("(-");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn3 && fn3.Name == "print-line")
        {
            sb.Append("std::cout << ");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(" << std::endl");
        }
        else if (app.Function is IRName fn4 && fn4.Name == "open-file")
        {
            sb.Append("std::ifstream(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn5 && fn5.Name == "read-all")
        {
            sb.Append("[&]{ std::ostringstream _ss; _ss << ");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".rdbuf(); return _ss.str(); }()");
        }
        else if (app.Function is IRName fn6 && fn6.Name == "close-file")
        {
            sb.Append("((void)0)");
        }
        else if (app.Function is IRName fn7 && fn7.Name == "text-length")
        {
            sb.Append("int64_t(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".size())");
        }
        else if (app.Function is IRName fn7b && fn7b.Name == "char-to-text")
        {
            sb.Append("std::string(1, (char)"); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn8 && fn8.Name == "is-letter")
        {
            sb.Append("(bool)std::isalpha((char)"); EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn9 && fn9.Name == "is-digit")
        {
            sb.Append("(bool)std::isdigit((char)"); EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn10 && fn10.Name == "is-whitespace")
        {
            sb.Append("(bool)std::isspace((char)"); EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn11 && fn11.Name == "text-to-integer")
        {
            sb.Append("int64_t(std::stoll(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))");
        }
        else if (app.Function is IRName fn11b && fn11b.Name == "integer-to-text")
        {
            sb.Append("std::to_string(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn12 && fn12.Name == "char-code")
        {
            EmitExpr(sb, app.Argument, indent);
        }
        else if (app.Function is IRName fn13 && fn13.Name == "code-to-char")
        {
            EmitExpr(sb, app.Argument, indent);
        }
        else if (app.Function is IRName fn14 && fn14.Name == "list-length")
        {
            sb.Append("int64_t(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".size())");
        }
        else if (TryEmitMultiArgBuiltin(sb, app, indent))
        {
        }
        else
        {
            EmitApplyGeneral(sb, app, indent);
        }
    }

    void EmitApplyGeneral(StringBuilder sb, IRApply app, int indent)
    {
        string? ctorName = FindConstructorName(app);
        if (ctorName is not null)
        {
            string variantType = m_ctorToVariant[ctorName] ?? Sanitize(ctorName);
            List<IRExpr> args = [];
            CollectApplyArgs(app, args);
            sb.Append($"{variantType}({Sanitize(ctorName)}{{");
            for (int i = 0; i < args.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                EmitExpr(sb, args[i], indent);
            }
            sb.Append("})");
        }
        else
        {
            string? defName = FindDefinitionName(app);
            if (defName is not null
                && m_definitionArity.TryGet(defName, out int arity)
                && arity > 1)
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                if (args.Count == arity)
                {
                    sb.Append(Sanitize(defName));
                    sb.Append('(');
                    for (int i = 0; i < args.Count; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        EmitExpr(sb, args[i], indent);
                    }
                    sb.Append(')');
                }
                else
                {
                    EmitExpr(sb, app.Function, indent);
                    sb.Append('(');
                    EmitExpr(sb, app.Argument, indent);
                    sb.Append(')');
                }
            }
            else
            {
                EmitExpr(sb, app.Function, indent);
                sb.Append('(');
                EmitExpr(sb, app.Argument, indent);
                sb.Append(')');
            }
        }
    }

    protected override void EmitBinary(StringBuilder sb, IRBinary bin, int indent)
    {
        switch (bin.Op)
        {
            case IRBinaryOp.AppendText:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" + ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.AppendList:
                sb.Append("[&]{ auto _l = ");
                EmitExpr(sb, bin.Left, indent);
                sb.Append("; auto _r = ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append("; _l.insert(_l.end(), _r.begin(), _r.end()); return _l; }()");
                break;

            case IRBinaryOp.ConsList:
                sb.Append("[&]{ auto _r = ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append("; _r.insert(_r.begin(), ");
                EmitExpr(sb, bin.Left, indent);
                sb.Append("); return _r; }()");
                break;

            case IRBinaryOp.PowInt:
                sb.Append("int64_t(std::pow(double(");
                EmitExpr(sb, bin.Left, indent);
                sb.Append("), double(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(")))");
                break;

            case IRBinaryOp.DivInt:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" / ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.Eq when IsTextType(bin.Left.Type):
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" == ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.NotEq when IsTextType(bin.Left.Type):
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" != ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            default:
                string op = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
                    IRBinaryOp.DivNum => "/",
                    IRBinaryOp.Eq => "==",
                    IRBinaryOp.NotEq => "!=",
                    IRBinaryOp.Lt => "<",
                    IRBinaryOp.Gt => ">",
                    IRBinaryOp.LtEq => "<=",
                    IRBinaryOp.GtEq => ">=",
                    IRBinaryOp.And => "&&",
                    IRBinaryOp.Or => "||",
                    _ => "+"
                };
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append($" {op} ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;
        }
    }

    protected override void EmitLet(StringBuilder sb, IRLet let, int indent)
    {
        sb.Append("[&]{ auto ");
        sb.Append(Sanitize(let.Name));
        sb.Append(" = ");
        EmitExpr(sb, let.Value, indent);
        sb.Append("; return ");
        EmitExpr(sb, let.Body, indent);
        sb.Append("; }()");
    }

    protected override void EmitLambda(StringBuilder sb, IRLambda lam, int indent)
    {
        sb.Append("[&](");
        for (int i = 0; i < lam.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"auto {Sanitize(lam.Parameters[i].Name)}");
        }
        sb.Append(") { return ");
        EmitExpr(sb, lam.Body, indent);
        sb.Append("; }");
    }

    protected override void EmitMatch(StringBuilder sb, IRMatch match, int indent)
    {
        sb.Append("std::visit([&](auto&& _s) -> ");
        sb.Append(EmitType(match.Type));
        sb.Append(" { ");

        bool first = true;
        int branchIdx = 0;
        foreach (IRMatchBranch branch in match.Branches)
        {
            string keyword = first ? "if" : " else if";
            first = false;
            branchIdx++;

            switch (branch.Pattern)
            {
                case IRCtorPattern ctorPat:
                    sb.Append($"{keyword} constexpr (std::is_same_v<std::decay_t<decltype(_s)>, {Sanitize(ctorPat.Name)}>) {{ ");
                    for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
                    {
                        if (ctorPat.SubPatterns[i] is IRVarPattern svp)
                            sb.Append($"auto {Sanitize(svp.Name)} = _s.field{i}; ");
                    }
                    sb.Append("return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; }");
                    break;

                case IRLiteralPattern litPat:
                    sb.Append($"{keyword} (_s == ");
                    EmitLiteralValue(sb, litPat.Value);
                    sb.Append(") { return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; }");
                    break;

                case IRVarPattern varPat:
                    sb.Append(" else { auto ");
                    sb.Append(Sanitize(varPat.Name));
                    sb.Append(" = _s; return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; }");
                    break;

                case IRWildcardPattern:
                    sb.Append(" else { return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; }");
                    break;
            }
        }

        if (first)
            sb.Append("return {}; ");
        else
            sb.Append(" else { throw std::runtime_error(\"non-exhaustive match\"); }");

        sb.Append(" }, ");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.Append(')');
    }

    void EmitActExpr(StringBuilder sb, IRAct actExpr, int indent)
    {
        sb.AppendLine("[&]{");
        string pad = new(' ', (indent + 1) * 4);
        foreach (IRActStatement stmt in actExpr.Statements)
        {
            switch (stmt)
            {
                case IRActBind bind:
                    sb.Append($"{pad}auto {Sanitize(bind.Name)} = ");
                    EmitExpr(sb, bind.Value, indent + 1);
                    sb.AppendLine(";");
                    break;
                case IRActExec exec:
                    sb.Append(pad);
                    EmitExpr(sb, exec.Expression, indent + 1);
                    sb.AppendLine(";");
                    break;
            }
        }
        sb.Append(new string(' ', indent * 4));
        sb.Append("}()");
    }

    void EmitStatement(StringBuilder sb, IRExpr expr, int indent)
    {
        string pad = new(' ', indent * 4);
        if (expr is IRAct actExpr)
        {
            foreach (IRActStatement stmt in actExpr.Statements)
            {
                switch (stmt)
                {
                    case IRActBind bind:
                        sb.Append($"{pad}auto {Sanitize(bind.Name)} = ");
                        EmitExpr(sb, bind.Value, indent);
                        sb.AppendLine(";");
                        break;
                    case IRActExec exec:
                        sb.Append(pad);
                        EmitExpr(sb, exec.Expression, indent);
                        sb.AppendLine(";");
                        break;
                }
            }
        }
        else
        {
            sb.Append(pad);
            EmitExpr(sb, expr, indent);
            sb.Append(';');
        }
    }

    bool TryEmitMultiArgBuiltin(StringBuilder sb, IRApply app, int indent)
    {
        string? name = FindBuiltinRoot(app);
        if (name is null) return false;

        List<IRExpr> args = [];
        CollectApplyArgs(app, args);

        switch (name)
        {
            case "char-at" when args.Count == 2:
                sb.Append("(int64_t)");
                EmitExpr(sb, args[0], indent);
                sb.Append("[(size_t)");
                EmitExpr(sb, args[1], indent);
                sb.Append(']');
                return true;

            case "substring" when args.Count == 3:
                EmitExpr(sb, args[0], indent);
                sb.Append(".substr(");
                EmitExpr(sb, args[1], indent);
                sb.Append(", ");
                EmitExpr(sb, args[2], indent);
                sb.Append(')');
                return true;

            case "list-at" when args.Count == 2:
                EmitExpr(sb, args[0], indent);
                sb.Append('[');
                EmitExpr(sb, args[1], indent);
                sb.Append(']');
                return true;

            case "text-replace" when args.Count == 3:
                sb.Append("[&]{ auto _s = ");
                EmitExpr(sb, args[0], indent);
                sb.Append("; auto _f = ");
                EmitExpr(sb, args[1], indent);
                sb.Append("; auto _t = ");
                EmitExpr(sb, args[2], indent);
                sb.Append("; size_t _p = 0; while ((_p = _s.find(_f, _p)) != std::string::npos) { ");
                sb.Append("_s.replace(_p, _f.size(), _t); _p += _t.size(); } return _s; }()");
                return true;

            default:
                return false;
        }
    }

    static void EmitLiteralValue(StringBuilder sb, object value)
    {
        switch (value)
        {
            case bool b:
                sb.Append(b ? "true" : "false");
                break;
            case long l:
                sb.Append($"int64_t({l})");
                break;
            case string s:
                sb.Append($"std::string(\"{EscapeString(s)}\")");
                break;
            default:
                sb.Append(value);
                break;
        }
    }

    static string EmitType(CodexType type)
    {
        return type switch
        {
            IntegerType => "int64_t",
            NumberType => "double",
            TextType => "std::string",
            BooleanType => "bool",
            NothingType => "void",
            VoidType => "void",
            EffectfulType eft => EmitType(eft.Return),
            LinearType lin => EmitType(lin.Inner),
            ListType lt => $"std::vector<{EmitType(lt.Element)}>",
            FunctionType ft => $"std::function<{EmitType(ft.Return)}({EmitType(ft.Parameter)})>",
            ForAllType fa => EmitType(fa.Body),
            RecordType rt => Sanitize(rt.TypeName.Value),
            SumType st => Sanitize(st.TypeName.Value),
            TypeVariable tv => $"T{tv.Id}",
            ErrorType => "auto",
            _ => "auto"
        };
    }

    string EmitReturnType(IRDefinition def)
    {
        CodexType type = def.PureReturnType();
        if (type is NothingType or VoidType) return "void";
        string t = EmitType(type);
        return t == "auto" ? "auto" : t;
    }


    static bool IsTextType(CodexType type) =>
        type is TextType;

    static string? FindConstructorName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && name.Name.Length > 0 && char.IsUpper(name.Name[0]))
            return name.Name;
        return null;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]))
            return name.Name;
        return null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner)
            CollectApplyArgs(inner, args);
        args.Add(app.Argument);
    }

    static readonly Set<string> s_multiArgBuiltins = Set<string>.Of(
        "char-at", "substring", "list-at", "text-replace");

    static string? FindBuiltinRoot(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        if (current is IRName name && s_multiArgBuiltins.Contains(name.Name))
            return name.Name;
        return null;
    }


    static Map<string, string> BuildCtorToVariantMap(IRChapter module)
    {
        Map<string, string> map = Map<string, string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            if (kv.Value is SumType sum)
            {
                string variantName = Sanitize(sum.TypeName.Value);
                foreach (SumConstructorType ctor in sum.Constructors)
                    map = map.Set(ctor.Name.Value, variantName);
            }
        }
        return map;
    }

    static bool HasSelfTailCall(IRDefinition def)
    {
        if (def.Parameters.Length == 0) return false;
        return def.Body.HasTailCall(def.Name);
    }



    static void CollectTypeVars(CodexType type, SortedSet<int> vars)
    {
        switch (type)
        {
            case TypeVariable tv:
                vars.Add(tv.Id);
                break;
            case FunctionType ft:
                CollectTypeVars(ft.Parameter, vars);
                CollectTypeVars(ft.Return, vars);
                break;
            case DependentFunctionType dep:
                CollectTypeVars(dep.ParamType, vars);
                CollectTypeVars(dep.Body, vars);
                break;
            case ListType lt:
                CollectTypeVars(lt.Element, vars);
                break;
            case EffectfulType eft:
                CollectTypeVars(eft.Return, vars);
                break;
            case LinearType lin:
                CollectTypeVars(lin.Inner, vars);
                break;
            case ForAllType fa:
                vars.Add(fa.VariableId);
                CollectTypeVars(fa.Body, vars);
                break;
        }
    }

    static string EmitTemplatePrefix(SortedSet<int> tvars)
    {
        if (tvars.Count == 0) return "";
        StringBuilder tb = new();
        tb.Append("template<");
        bool first = true;
        foreach (int id in tvars)
        {
            if (!first) tb.Append(", ");
            first = false;
            tb.Append($"typename T{id}");
        }
        tb.Append('>');
        return tb.ToString();
    }

    static string Sanitize(string name) =>
        NameSanitizer.Sanitize(name, s_reservedKeywords, escapePrefix: "_");

    static readonly HashSet<string> s_reservedKeywords =
    [
        "class", "struct", "void", "return", "if", "else", "for",
        "while", "do", "switch", "case", "break", "continue",
        "new", "this", "null", "true", "false", "int", "long",
        "auto", "const", "static", "virtual", "override", "template",
        "typename", "namespace", "using", "public", "private",
        "protected", "friend", "operator", "delete", "default",
        "throw", "try", "catch", "inline", "extern", "register",
        "volatile", "mutable", "explicit", "export", "typedef",
        "double", "float", "char", "short", "bool", "unsigned",
        "signed", "sizeof", "alignof", "decltype", "constexpr",
        "noexcept", "nullptr", "string", "vector", "map", "set",
        "abs", "max", "min", "swap", "move", "sort", "main",
    ];

    static string EscapeString(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\n", "\\n")
        .Replace("\r", "\\r")
        .Replace("\t", "\\t");
}
