import {spawn,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,copyFileSync,rmSync,lstatSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createServer} from 'node:net';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const repo=resolve(fileURLToPath(new URL('../..',import.meta.url))),out=join(repo,'build-output/native-deploy');
const scratch=mkdtempSync(join(tmpdir(),'modbuilder-deploy-')),game=join(scratch,'Steam é/steamapps/common/Valheim'),dest=join(scratch,'Play é'),local=join(scratch,'local');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
for(const root of [game,dest])for(const name of ['valheim.exe','UnityPlayer.dll','valheim_Data/Managed/assembly_valheim.dll','MonoBleedingEdge/EmbedRuntime/mono-2.0-bdwgc.dll']){const path=join(root,name);mkdirSync(resolve(path,'..'),{recursive:true});writeFileSync(path,'deployment browser fixture');}
mkdirSync(local,{recursive:true});mkdirSync(join(scratch,'Desktop'));
const newTarget=join(scratch,'Custom target é');mkdirSync(newTarget);
const dll=join(scratch,'Desktop/PrismMod.dll');copyFileSync(join(repo,'codex/plugs/cil/build-output/test/unity-hud.dll'),dll);
copyFileSync(join(repo,'apps/modbuilder/web/workspace.html'),join(scratch,'workspace.html'));
const capture=join(scratch,'Capture.codex'),launchLog=join(scratch,'launch.txt');
writeFileSync(capture,readFileSync(join(repo,'apps/modbuilder/native/WindowsHost.codex'),'utf8')+'\nChapter: Browser Launch Capture\n  opening : [Console] Nothing =\n   let h = mb-host 0\n   in let command = mb-from-wide (mb-call (h.command) 0 0 0 0 0 0 0 0) 32768\n   in let saved = mb-write h (mb-env h "MODBUILDER_TEST_CAPTURE_LOG") command\n   in print-line-uni (if saved then "captured" else "failed")\n');
const built=spawnSync('node',[join(repo,'apps/modbuilder/native/build-helper.mjs'),capture,join(dest,'valheim.exe')],{encoding:'utf8',windowsHide:true});assert.equal(built.status,0,built.stdout+built.stderr);
const helper=spawn(join(out,'ModBuilder.exe'),['--test'],{windowsHide:true,env:{...process.env,LOCALAPPDATA:local,MODBUILDER_TEST_CAPTURE_LOG:launchLog,MODBUILDER_TEST_STEAM:join(scratch,'Steam é'),MODBUILDER_TEST_DEST:dest,MODBUILDER_TEST_NEW_DEST:newTarget,MODBUILDER_TEST_GAME_HASH:sha(readFileSync(join(game,'valheim_Data/Managed/assembly_valheim.dll'))),MODBUILDER_TEST_PLAYER_HASH:sha(readFileSync(join(game,'UnityPlayer.dll'))),MODBUILDER_TEST_RUNNING:'0'},stdio:['ignore','pipe','pipe']});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let edge,ws;
try{
  const ready=await new Promise((resolve,reject)=>{let text='';const timer=setTimeout(()=>reject(new Error('Native helper startup timeout')),10000);helper.stdout.on('data',chunk=>{text+=chunk.toString();if(text.includes('\n')){clearTimeout(timer);try{resolve(JSON.parse(text.trim()));}catch(error){reject(error);}}});helper.on('error',reject);helper.on('exit',code=>{clearTimeout(timer);reject(new Error('Helper exited '+code));});});
  const probe=createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
  edge=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--no-first-run','--remote-debugging-port='+port,'--user-data-dir='+join(scratch,'profile'),'about:blank'],{stdio:'ignore',windowsHide:true});
  let target;for(let i=0;i<80&&!target;i++){try{target=(await(await fetch('http://127.0.0.1:'+port+'/json/list')).json()).find(t=>t.type==='page');}catch{}if(!target)await sleep(200);}assert(target);
  ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r));let id=0;const pending=new Map();
  ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id){pending.get(message.id)?.(message);pending.delete(message.id);}});
  const send=(method,params={})=>new Promise(r=>{const number=++id;pending.set(number,r);ws.send(JSON.stringify({id:number,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(result.error||result.result?.exceptionDetails)throw new Error(JSON.stringify(result));return result.result.result.value;};
  const until=async expression=>{for(let i=0;i<160;i++){if(await evaluate(expression))return;await sleep(100);}throw new Error('Timed out: '+expression);};
  await send('Page.navigate',{url:pathToFileURL(join(scratch,'workspace.html')).href+'#bridge='+ready.token+'&bridgeUrl='+encodeURIComponent('http://127.0.0.1:18789')});
  await until(`!!document.getElementById('mb-deploy-now')&&!document.getElementById('mb-deploy-choose').disabled`);
  assert(await evaluate(`document.querySelector('input[name="mb-target-choice"]:checked').value==='new'&&!document.getElementById('mb-new-target').hidden&&document.getElementById('mb-existing-target').hidden`),'no default copy selects creation and shows the new-folder action');
  await evaluate(`(async()=>{window.actualDeployFetch=window.fetch;window.fetch=async(...args)=>{const response=await window.actualDeployFetch(...args);if(String(args[0]).endsWith('/health')){const data=await response.json();data.capabilities.install=false;return new Response(JSON.stringify(data));}return response;};await document.getElementById('mb-deploy-check').onclick();})()`);
  assert(await evaluate(`!document.getElementById('mb-deploy-update').hidden&&document.getElementById('mb-deploy-now').disabled&&document.getElementById('mb-deploy-status').textContent.includes('updated helper')`),'older helper receives an explicit update path');
  await evaluate(`(async()=>{window.fetch=window.actualDeployFetch;await document.getElementById('mb-deploy-check').onclick();})()`);
  await evaluate(`document.getElementById('mb-deploy-card').open=true;document.querySelector('input[name="mb-target-choice"][value="existing"]').click();document.getElementById('mb-deploy-choose').click()`);
  await until(`document.getElementById('mb-deploy-destination').textContent.includes('Play')&&!document.getElementById('mb-deploy-file').disabled`);
  const doc=await send('DOM.getDocument'),input=await send('DOM.querySelector',{nodeId:doc.result.root.nodeId,selector:'#mb-deploy-file'});
  await send('DOM.setFileInputFiles',{nodeId:input.result.nodeId,files:[dll]});
  await until(`!document.getElementById('mb-deploy-now').disabled`);
  await evaluate(`document.getElementById('mb-deploy-now').click()`);
  await until(`document.getElementById('mb-deploy-card').classList.contains('done')`);
  assert(await evaluate(`document.getElementById('mb-deploy-card').open&&document.getElementById('mb-deploy-card').contains(document.getElementById('mb-launch-card'))&&document.getElementById('mb-deploy-receipt').textContent.includes('winhttp.dll')&&document.getElementById('mb-deploy-receipt').textContent.includes('Backup:')`),'deployment keeps launch and its receipt in the same card');
  const receipt=JSON.parse(readFileSync(join(dest,'Support/deployment.json'),'utf8'));
  assert.equal(sha(readFileSync(join(dest,'winhttp.dll'))),receipt.modHash);
  assert(await evaluate(`document.getElementById('mb-deploy-artifact').textContent.includes(${JSON.stringify(receipt.buildNumber)})&&document.getElementById('mb-launch-build').textContent.includes(${JSON.stringify(receipt.buildNumber)})`),'selected DLL and launch card show the native build identifier');
  assert(await evaluate(`document.getElementById('mb-developer-setup').hidden&&document.getElementById('mb-developer-setup').getBoundingClientRect().height===0`),'previous bridge section is absent from the player view');
  await until(`!document.getElementById('mb-launch-now').disabled`);
  await evaluate(`document.getElementById('mb-launch-now').onclick()`);
  assert(await evaluate(`document.getElementById('mb-launch-status').textContent.includes('isolated Saves')`),'launch reports the actual native refusal without claiming the game started');
  mkdirSync(join(dest,'Saves'));writeFileSync(join(dest,'prism-local-saves.marker'),'Prism local saves');
  await evaluate(`document.getElementById('mb-launch-now').onclick()`);
  assert(await evaluate(`document.getElementById('mb-deploy-card').classList.contains('done')&&document.querySelector('.mb-launch-result').textContent==='Launch requested'&&document.getElementById('mb-launch-status').textContent.includes(${JSON.stringify(receipt.buildNumber)})`),'launch acceptance displays the installed build without claiming game readiness');
  let launched='';for(let i=0;i<50&&!launched;i++){try{launched=readFileSync(launchLog,'utf8');}catch{}if(!launched)await sleep(100);}
  assert(launched.includes('"'+join(dest,'Saves')+'"'),'page launch reaches the native capture process with separate saves');
  assert(readFileSync(join(receipt.backup,'PrismMod.dll')).equals(readFileSync(dll)),'helper archives exactly the saved DLL chosen in the browser');
  assert.equal(readFileSync(join(game,'valheim.exe'),'utf8'),'deployment browser fixture');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await evaluate(`document.getElementById('mb-deploy-card').open=true`);
  await evaluate(`document.getElementById('mb-deploy-check').onclick()`);
  assert(await evaluate(`document.getElementById('mb-deploy-card').querySelector('.mb-step-result').textContent.startsWith('Deployed to')`),'reopening the deployment card preserves its completed receipt');
  assert(await evaluate(`document.getElementById('mb-redeploy-note').textContent.includes(${JSON.stringify(receipt.buildNumber)})&&document.getElementById('mb-redeploy-note').textContent.includes('backs up')`),'redeployment identifies the existing build and backup before confirmation');
  assert(await evaluate(`document.documentElement.scrollWidth<=400`),'deployment paths fit a narrow screen');
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});writeFileSync(join(out,'deployment-page.png'),Buffer.from(shot.result.data,'base64'));
  await evaluate(`document.querySelector('input[name="mb-target-choice"][value="new"]').click();document.getElementById('mb-copy-type').value='light';document.getElementById('mb-copy-type').dispatchEvent(new Event('change'));document.getElementById('mb-deploy-create').click()`);
  await until(`document.getElementById('mb-deploy-destination').textContent.includes('Valheim-Light')&&!document.getElementById('mb-deploy-create').disabled`);
  assert(lstatSync(join(scratch,'Steam é/ModBuilder/Valheim-Light/valheim_Data')).isSymbolicLink(),'website lightweight choice creates shared-data junctions');
  await evaluate(`document.querySelector('input[name="mb-target-choice"][value="new"]').click();document.getElementById('mb-copy-type').value='full';document.getElementById('mb-copy-type').dispatchEvent(new Event('change'));document.getElementById('mb-deploy-create').click()`);
  await until(`document.getElementById('mb-deploy-destination').textContent.includes('Full target:')&&!document.getElementById('mb-deploy-create').disabled`);
  assert(!lstatSync(join(scratch,'Steam é/ModBuilder/Valheim/valheim_Data')).isSymbolicLink(),'website full choice creates private game data');
  await evaluate(`document.querySelector('input[name="mb-target-choice"][value="new"]').click()`);
  assert(await evaluate(`document.getElementById('mb-deploy-now').disabled&&document.getElementById('mb-launch-now').disabled`),'choosing a new target prevents deploying to the previously selected copy');
  await evaluate(`document.getElementById('mb-copy-type').value='light';document.getElementById('mb-deploy-create-folder').click()`);
  await until(`document.getElementById('mb-deploy-destination').textContent.includes('Custom target')&&!document.getElementById('mb-deploy-file').disabled`);
  assert(lstatSync(join(newTarget,'valheim_Data')).isSymbolicLink(),'new-target folder selection prepares the exact chosen folder');
  assert(await evaluate(`document.querySelector('input[name="mb-target-choice"]:checked').value==='existing'&&document.getElementById('mb-new-target').hidden`),'a prepared target becomes the active existing destination');
  console.log('PASS saved desktop DLL deploys through file-mode page and native helper, with backup and receipt');
}finally{ws?.close();edge?.kill();helper.kill();await sleep(800);assert(scratch.startsWith(tmpdir()));try{rmSync(scratch,{recursive:true,force:true});}catch{}}
